import { shuffle } from "lodash";

const trackMich = {
  spotifyId: "1OOtq8tRnDM8kG2gqUPjAj",
  spotifyUri: "spotify:track:1OOtq8tRnDM8kG2gqUPjAj",
  spotifyAlbumId: "1C2h7mLntPSeVYciMRTF4a",
  name: "Beat It",
  spotifyArtistsIds: ["3fMbdgg4jU18AjLCKBhRSm"],
  spotifyDurationMS: 258040,
  spotifyIsExplicit: false,
  spotifyIsPlayable: false,
  spotifyPreviewURL:
    "https://p.scdn.co/mp3-preview/1b0b8d9493dbbdb4c2a4792ce850787ad8052ecb?cid=7c4c757477e2485ea783355e72a900af",
  spotifyTrackAlbumPos: 5,
  spotifyDiscNumber: 1,
  spotifyUrl: "https://open.spotify.com/track/1OOtq8tRnDM8kG2gqUPjAj",
  artists: [
    {
      name: "Michael Jackson",
      spotifyId: "3fMbdgg4jU18AjLCKBhRSm",
      spotifyUri: "spotify:artist:3fMbdgg4jU18AjLCKBhRSm",
      spotifyUrl: "https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm",
      spotifyGenres: ["pop", "r&b", "soul"],
      spotifyPopularity: 80,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eba2a0b9e3448c1e702de9dc90",
        "https://i.scdn.co/image/ab67616100005174a2a0b9e3448c1e702de9dc90",
        "https://i.scdn.co/image/ab6761610000f178a2a0b9e3448c1e702de9dc90",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eba2a0b9e3448c1e702de9dc90",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174a2a0b9e3448c1e702de9dc90",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178a2a0b9e3448c1e702de9dc90",
          width: 160,
        },
      ],
      type: "artist",
      id: 704,
    },
  ],
  genreVersion: 0,
  isSaved: false,
  spotifyPopularity: 80,
  type: "track",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  album: {
    spotifyId: "1C2h7mLntPSeVYciMRTF4a",
    name: "Thriller 25 Super Deluxe Edition",
    spotifyCoverUrl: [
      "https://i.scdn.co/image/ab67616d0000b2734121faee8df82c526cbab2be",
      "https://i.scdn.co/image/ab67616d00001e024121faee8df82c526cbab2be",
      "https://i.scdn.co/image/ab67616d000048514121faee8df82c526cbab2be",
    ],
    spotifyCovers: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b2734121faee8df82c526cbab2be",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e024121faee8df82c526cbab2be",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d000048514121faee8df82c526cbab2be",
        width: 64,
      },
    ],
    spotifyUrl: "https://open.spotify.com/album/1C2h7mLntPSeVYciMRTF4a",
    spotifyReleaseDate: new Date("1982-11-29T23:00:00.000Z"),
    spotifyArtistsIds: ["3fMbdgg4jU18AjLCKBhRSm"],
    spotifyPopularity: 74,
    spotifyGenres: [],
    spotifyUri: "spotify:album:1C2h7mLntPSeVYciMRTF4a",
    albumTags: [],
    artists: [
      {
        name: "Michael Jackson",
        spotifyId: "3fMbdgg4jU18AjLCKBhRSm",
        spotifyUri: "spotify:artist:3fMbdgg4jU18AjLCKBhRSm",
        spotifyUrl: "https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm",
        spotifyGenres: ["pop", "r&b", "soul"],
        spotifyPopularity: 80,
        spotifyImgs: [
          "https://i.scdn.co/image/ab6761610000e5eba2a0b9e3448c1e702de9dc90",
          "https://i.scdn.co/image/ab67616100005174a2a0b9e3448c1e702de9dc90",
          "https://i.scdn.co/image/ab6761610000f178a2a0b9e3448c1e702de9dc90",
        ],
        spotifyArtistImgs: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6761610000e5eba2a0b9e3448c1e702de9dc90",
            width: 640,
          },
          {
            height: 320,
            url: "https://i.scdn.co/image/ab67616100005174a2a0b9e3448c1e702de9dc90",
            width: 320,
          },
          {
            height: 160,
            url: "https://i.scdn.co/image/ab6761610000f178a2a0b9e3448c1e702de9dc90",
            width: 160,
          },
        ],
        type: "artist",
        id: 704,
      },
    ],
    lastfmTagsNames: [
      "pop",
      "80s",
      "soul",
      "albums I own",
      "funk",
      "old school",
      "michael jackson",
      "king of pop",
      "dance",
      "r&b",
      "male vocalists",
      "d",
    ],
    type: "album",
    markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CD",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IQ",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    lastfmTagsFull: [
      {
        name: "pop",
        url: "https://www.last.fm/tag/pop",
      },
      {
        name: "80s",
        url: "https://www.last.fm/tag/80s",
      },
      {
        name: "soul",
        url: "https://www.last.fm/tag/soul",
      },
      {
        name: "albums I own",
        url: "https://www.last.fm/tag/albums+I+own",
      },
      {
        name: "funk",
        url: "https://www.last.fm/tag/funk",
      },
      {
        name: "old school",
        url: "https://www.last.fm/tag/old+school",
      },
      {
        name: "michael jackson",
        url: "https://www.last.fm/tag/michael+jackson",
      },
      {
        name: "king of pop",
        url: "https://www.last.fm/tag/king+of+pop",
      },
      {
        name: "dance",
        url: "https://www.last.fm/tag/dance",
      },
      {
        name: "r&b",
        url: "https://www.last.fm/tag/r&b",
      },
      {
        name: "male vocalists",
        url: "https://www.last.fm/tag/male+vocalists",
      },
      {
        name: "d",
        url: "https://www.last.fm/tag/d",
      },
    ],
    id: 672,
  },
  id: 607,
  ludwigGenres: [
    {
      label: "pop",
      confidence: 0.2620595693588257,
    },
  ],
  ludwigMoods: [
    {
      label: "happy",
      confidence: 0.7548925280570984,
    },
    {
      label: "sad",
      confidence: 0.10951784998178482,
    },
    {
      label: "party",
      confidence: 0.6641157865524292,
    },
    {
      label: "relaxed",
      confidence: 0.1606413871049881,
    },
    {
      label: "acoustic",
      confidence: 0.15503880381584167,
    },
    {
      label: "electronic",
      confidence: 0.4499354958534241,
    },
    {
      label: "aggressive",
      confidence: 0.7013453245162964,
    },
  ],
  ludwigSubgenres: [
    {
      label: "pop---rhythm & blues",
      confidence: 0.525751531124115,
    },
    {
      label: "pop---soul",
      confidence: 0.47152602672576904,
    },
  ],
};

const trackMine = {
  spotifyId: "4NsPgRYUdHu2Q5JRNgXYU5",
  spotifyUri: "spotify:track:4NsPgRYUdHu2Q5JRNgXYU5",
  spotifyAlbumId: "3Gt7rOjcZQoHCfnKl5AkK7",
  name: "Sweden",
  spotifyArtistsIds: ["4uFZsG1vXrPcvnZ4iSQyrx"],
  spotifyDurationMS: 215500,
  spotifyIsExplicit: false,
  spotifyIsPlayable: false,
  spotifyPreviewURL:
    "https://p.scdn.co/mp3-preview/ab6298f302f9d3c8abd4943b529c3cbf56a68787?cid=7c4c757477e2485ea783355e72a900af",
  spotifyTrackAlbumPos: 18,
  spotifyDiscNumber: 1,
  spotifyUrl: "https://open.spotify.com/track/4NsPgRYUdHu2Q5JRNgXYU5",
  artists: [
    {
      name: "C418",
      spotifyId: "4uFZsG1vXrPcvnZ4iSQyrx",
      spotifyUri: "spotify:artist:4uFZsG1vXrPcvnZ4iSQyrx",
      spotifyUrl: "https://open.spotify.com/artist/4uFZsG1vXrPcvnZ4iSQyrx",
      spotifyGenres: ["dream smp", "minecraft"],
      spotifyPopularity: 67,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eba9b8234e3071836212561d19",
        "https://i.scdn.co/image/ab67616100005174a9b8234e3071836212561d19",
        "https://i.scdn.co/image/ab6761610000f178a9b8234e3071836212561d19",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eba9b8234e3071836212561d19",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174a9b8234e3071836212561d19",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178a9b8234e3071836212561d19",
          width: 160,
        },
      ],
      type: "artist",
      id: 734,
    },
  ],
  genreVersion: 0,
  isSaved: false,
  spotifyPopularity: 66,
  type: "track",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BZ",
    "CA",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "ZA",
    "ZM",
  ],
  album: {
    spotifyId: "3Gt7rOjcZQoHCfnKl5AkK7",
    name: "Minecraft - Volume Alpha",
    spotifyCoverUrl: [
      "https://i.scdn.co/image/ab67616d0000b273aaeb5c9fb6131977995b7f0e",
      "https://i.scdn.co/image/ab67616d00001e02aaeb5c9fb6131977995b7f0e",
      "https://i.scdn.co/image/ab67616d00004851aaeb5c9fb6131977995b7f0e",
    ],
    spotifyCovers: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273aaeb5c9fb6131977995b7f0e",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02aaeb5c9fb6131977995b7f0e",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851aaeb5c9fb6131977995b7f0e",
        width: 64,
      },
    ],
    spotifyUrl: "https://open.spotify.com/album/3Gt7rOjcZQoHCfnKl5AkK7",
    spotifyReleaseDate: new Date("2011-03-03T23:00:00.000Z"),
    spotifyArtistsIds: ["4uFZsG1vXrPcvnZ4iSQyrx"],
    spotifyPopularity: 67,
    spotifyGenres: [],
    spotifyUri: "spotify:album:3Gt7rOjcZQoHCfnKl5AkK7",
    albumTags: [],
    artists: [
      {
        name: "C418",
        spotifyId: "4uFZsG1vXrPcvnZ4iSQyrx",
        spotifyUri: "spotify:artist:4uFZsG1vXrPcvnZ4iSQyrx",
        spotifyUrl: "https://open.spotify.com/artist/4uFZsG1vXrPcvnZ4iSQyrx",
        spotifyGenres: ["dream smp", "minecraft"],
        spotifyPopularity: 67,
        spotifyImgs: [
          "https://i.scdn.co/image/ab6761610000e5eba9b8234e3071836212561d19",
          "https://i.scdn.co/image/ab67616100005174a9b8234e3071836212561d19",
          "https://i.scdn.co/image/ab6761610000f178a9b8234e3071836212561d19",
        ],
        spotifyArtistImgs: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6761610000e5eba9b8234e3071836212561d19",
            width: 640,
          },
          {
            height: 320,
            url: "https://i.scdn.co/image/ab67616100005174a9b8234e3071836212561d19",
            width: 320,
          },
          {
            height: 160,
            url: "https://i.scdn.co/image/ab6761610000f178a9b8234e3071836212561d19",
            width: 160,
          },
        ],
        type: "artist",
        id: 734,
      },
    ],
    lastfmTagsNames: [
      "ambient",
      "2011",
      "electronic",
      "Soundtrack",
      "video game music",
      "Impressionism",
      "minecraft",
      "chillout",
      "10s",
      "Progressive Electronic",
      "electronica",
      "indie",
    ],
    type: "album",
    markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BZ",
      "CA",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "VU",
      "WS",
      "ZA",
      "ZM",
    ],
    lastfmTagsFull: [
      {
        name: "ambient",
        url: "https://www.last.fm/tag/ambient",
      },
      {
        name: "2011",
        url: "https://www.last.fm/tag/2011",
      },
      {
        name: "electronic",
        url: "https://www.last.fm/tag/electronic",
      },
      {
        name: "Soundtrack",
        url: "https://www.last.fm/tag/Soundtrack",
      },
      {
        name: "video game music",
        url: "https://www.last.fm/tag/video+game+music",
      },
      {
        name: "Impressionism",
        url: "https://www.last.fm/tag/Impressionism",
      },
      {
        name: "minecraft",
        url: "https://www.last.fm/tag/minecraft",
      },
      {
        name: "chillout",
        url: "https://www.last.fm/tag/chillout",
      },
      {
        name: "10s",
        url: "https://www.last.fm/tag/10s",
      },
      {
        name: "Progressive Electronic",
        url: "https://www.last.fm/tag/Progressive+Electronic",
      },
      {
        name: "electronica",
        url: "https://www.last.fm/tag/electronica",
      },
      {
        name: "indie",
        url: "https://www.last.fm/tag/indie",
      },
    ],
    id: 690,
  },
  id: 628,
  ludwigGenres: [
    {
      label: "classical",
      confidence: 0.8050779700279236,
    },
  ],
  ludwigMoods: [
    {
      label: "happy",
      confidence: 0.03425159305334091,
    },
    {
      label: "sad",
      confidence: 0.9945194721221924,
    },
    {
      label: "party",
      confidence: 0.060908250510692596,
    },
    {
      label: "relaxed",
      confidence: 0.9922740459442139,
    },
    {
      label: "acoustic",
      confidence: 0.9583628177642822,
    },
    {
      label: "electronic",
      confidence: 0.20464852452278137,
    },
    {
      label: "aggressive",
      confidence: 0.1622866839170456,
    },
  ],
  ludwigSubgenres: [
    {
      label: "classical---classical",
      confidence: 0.47890710830688477,
    },
    {
      label: "classical---romantic",
      confidence: 0.594435453414917,
    },
    {
      label: "classical---modern",
      confidence: 0.4145897626876831,
    },
  ],
};

const trackBowie = {
  spotifyId: "3ix6K4wZY29bCujrSznwFZ",
  spotifyUri: "spotify:track:3ix6K4wZY29bCujrSznwFZ",
  spotifyAlbumId: "4NwG11AsDJluT732lSjMrV",
  name: "Let's Dance - 2018 Remaster",
  spotifyArtistsIds: ["0oSGxfWSnnOXhD2fKuz2Gy"],
  spotifyDurationMS: 457675,
  spotifyIsExplicit: false,
  spotifyIsPlayable: false,
  spotifyPreviewURL:
    "https://p.scdn.co/mp3-preview/c4e3a1947b76b200b3b2cbf9810ca178e9f53823?cid=7c4c757477e2485ea783355e72a900af",
  spotifyTrackAlbumPos: 3,
  spotifyDiscNumber: 1,
  spotifyUrl: "https://open.spotify.com/track/3ix6K4wZY29bCujrSznwFZ",
  artists: [
    {
      name: "David Bowie",
      spotifyId: "0oSGxfWSnnOXhD2fKuz2Gy",
      spotifyUri: "spotify:artist:0oSGxfWSnnOXhD2fKuz2Gy",
      spotifyUrl: "https://open.spotify.com/artist/0oSGxfWSnnOXhD2fKuz2Gy",
      spotifyGenres: [
        "art rock",
        "classic rock",
        "glam rock",
        "permanent wave",
        "rock",
      ],
      spotifyPopularity: 75,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5ebb78f77c5583ae99472dd4a49",
        "https://i.scdn.co/image/ab67616100005174b78f77c5583ae99472dd4a49",
        "https://i.scdn.co/image/ab6761610000f178b78f77c5583ae99472dd4a49",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebb78f77c5583ae99472dd4a49",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174b78f77c5583ae99472dd4a49",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178b78f77c5583ae99472dd4a49",
          width: 160,
        },
      ],
      type: "artist",
      id: 701,
    },
  ],
  genreVersion: 0,
  isSaved: false,
  spotifyPopularity: 72,
  type: "track",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  album: {
    spotifyId: "4NwG11AsDJluT732lSjMrV",
    name: "Let's Dance (2018 Remaster)",
    spotifyCoverUrl: [
      "https://i.scdn.co/image/ab67616d0000b273db0917ddd4139153bc1d1a1a",
      "https://i.scdn.co/image/ab67616d00001e02db0917ddd4139153bc1d1a1a",
      "https://i.scdn.co/image/ab67616d00004851db0917ddd4139153bc1d1a1a",
    ],
    spotifyCovers: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273db0917ddd4139153bc1d1a1a",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02db0917ddd4139153bc1d1a1a",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851db0917ddd4139153bc1d1a1a",
        width: 64,
      },
    ],
    spotifyUrl: "https://open.spotify.com/album/4NwG11AsDJluT732lSjMrV",
    spotifyReleaseDate: new Date("1983-04-13T22:00:00.000Z"),
    spotifyArtistsIds: ["0oSGxfWSnnOXhD2fKuz2Gy"],
    spotifyPopularity: 61,
    spotifyGenres: [],
    spotifyUri: "spotify:album:4NwG11AsDJluT732lSjMrV",
    albumTags: [],
    artists: [
      {
        name: "David Bowie",
        spotifyId: "0oSGxfWSnnOXhD2fKuz2Gy",
        spotifyUri: "spotify:artist:0oSGxfWSnnOXhD2fKuz2Gy",
        spotifyUrl: "https://open.spotify.com/artist/0oSGxfWSnnOXhD2fKuz2Gy",
        spotifyGenres: [
          "art rock",
          "classic rock",
          "glam rock",
          "permanent wave",
          "rock",
        ],
        spotifyPopularity: 75,
        spotifyImgs: [
          "https://i.scdn.co/image/ab6761610000e5ebb78f77c5583ae99472dd4a49",
          "https://i.scdn.co/image/ab67616100005174b78f77c5583ae99472dd4a49",
          "https://i.scdn.co/image/ab6761610000f178b78f77c5583ae99472dd4a49",
        ],
        spotifyArtistImgs: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6761610000e5ebb78f77c5583ae99472dd4a49",
            width: 640,
          },
          {
            height: 320,
            url: "https://i.scdn.co/image/ab67616100005174b78f77c5583ae99472dd4a49",
            width: 320,
          },
          {
            height: 160,
            url: "https://i.scdn.co/image/ab6761610000f178b78f77c5583ae99472dd4a49",
            width: 160,
          },
        ],
        type: "artist",
        id: 701,
      },
    ],
    lastfmTagsNames: [
      "classic rock",
      "rock",
      "80s",
      "alternative",
      "glam rock",
    ],
    type: "album",
    markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CD",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IQ",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    lastfmTagsFull: [
      {
        name: "classic rock",
        url: "https://www.last.fm/tag/classic+rock",
      },
      {
        name: "rock",
        url: "https://www.last.fm/tag/rock",
      },
      {
        name: "80s",
        url: "https://www.last.fm/tag/80s",
      },
      {
        name: "alternative",
        url: "https://www.last.fm/tag/alternative",
      },
      {
        name: "glam rock",
        url: "https://www.last.fm/tag/glam+rock",
      },
    ],
    id: 713,
  },
  id: 656,
  ludwigGenres: [
    {
      label: "rock",
      confidence: 0.62777518033981323,
    },
  ],
  ludwigMoods: [
    {
      label: "happy",
      confidence: 0.6616283059120178,
    },
    {
      label: "sad",
      confidence: 0.023377619683742523,
    },
    {
      label: "acoustic",
      confidence: 0.07082211971282959,
    },
    {
      label: "aggressive",
      confidence: 0.6686484813690186,
    },
    {
      label: "relaxed",
      confidence: 0.18416333198547363,
    },
    {
      label: "electronic",
      confidence: 0.7354053854942322,
    },
  ],
  ludwigSubgenres: [
    {
      label: "rock---blues",
      confidence: 0.8167906999588013,
    },
  ],
};

const trackCash = {
  spotifyId: "3I1vEQhGwRK7URrTq4BqNl",
  spotifyUri: "spotify:track:3I1vEQhGwRK7URrTq4BqNl",
  spotifyAlbumId: "5LWsHgqyGqhd6HNBYLb6W7",
  name: "(Ghost) Riders in the Sky",
  spotifyArtistsIds: ["6kACVPfCOnqzgfEF5ryl0x"],
  spotifyDurationMS: 224813,
  spotifyIsExplicit: false,
  spotifyIsPlayable: false,
  spotifyPreviewURL:
    "https://p.scdn.co/mp3-preview/70d4d6214b61483b3b3bc41e50151d76bf0b07de?cid=7c4c757477e2485ea783355e72a900af",
  spotifyTrackAlbumPos: 5,
  spotifyDiscNumber: 1,
  spotifyUrl: "https://open.spotify.com/track/3I1vEQhGwRK7URrTq4BqNl",
  artists: [
    {
      name: "Johnny Cash",
      spotifyId: "6kACVPfCOnqzgfEF5ryl0x",
      spotifyUri: "spotify:artist:6kACVPfCOnqzgfEF5ryl0x",
      spotifyUrl: "https://open.spotify.com/artist/6kACVPfCOnqzgfEF5ryl0x",
      spotifyGenres: ["arkansas country", "outlaw country"],
      spotifyPopularity: 73,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb152cf48cf9541c7061570857",
        "https://i.scdn.co/image/ab67616100005174152cf48cf9541c7061570857",
        "https://i.scdn.co/image/ab6761610000f178152cf48cf9541c7061570857",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb152cf48cf9541c7061570857",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174152cf48cf9541c7061570857",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178152cf48cf9541c7061570857",
          width: 160,
        },
      ],
      type: "artist",
      id: 768,
    },
  ],
  genreVersion: 0,
  isSaved: false,
  spotifyPopularity: 62,
  type: "track",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  album: {
    spotifyId: "5LWsHgqyGqhd6HNBYLb6W7",
    name: "Silver",
    spotifyCoverUrl: [
      "https://i.scdn.co/image/ab67616d0000b27379d1be381026d9bbd0de591b",
      "https://i.scdn.co/image/ab67616d00001e0279d1be381026d9bbd0de591b",
      "https://i.scdn.co/image/ab67616d0000485179d1be381026d9bbd0de591b",
    ],
    spotifyCovers: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b27379d1be381026d9bbd0de591b",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e0279d1be381026d9bbd0de591b",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d0000485179d1be381026d9bbd0de591b",
        width: 64,
      },
    ],
    spotifyUrl: "https://open.spotify.com/album/5LWsHgqyGqhd6HNBYLb6W7",
    spotifyReleaseDate: new Date("1979-04-30T22:00:00.000Z"),
    spotifyArtistsIds: ["6kACVPfCOnqzgfEF5ryl0x"],
    spotifyPopularity: 48,
    spotifyGenres: [],
    spotifyUri: "spotify:album:5LWsHgqyGqhd6HNBYLb6W7",
    albumTags: [],
    artists: [
      {
        name: "Johnny Cash",
        spotifyId: "6kACVPfCOnqzgfEF5ryl0x",
        spotifyUri: "spotify:artist:6kACVPfCOnqzgfEF5ryl0x",
        spotifyUrl: "https://open.spotify.com/artist/6kACVPfCOnqzgfEF5ryl0x",
        spotifyGenres: ["arkansas country", "outlaw country"],
        spotifyPopularity: 73,
        spotifyImgs: [
          "https://i.scdn.co/image/ab6761610000e5eb152cf48cf9541c7061570857",
          "https://i.scdn.co/image/ab67616100005174152cf48cf9541c7061570857",
          "https://i.scdn.co/image/ab6761610000f178152cf48cf9541c7061570857",
        ],
        spotifyArtistImgs: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6761610000e5eb152cf48cf9541c7061570857",
            width: 640,
          },
          {
            height: 320,
            url: "https://i.scdn.co/image/ab67616100005174152cf48cf9541c7061570857",
            width: 320,
          },
          {
            height: 160,
            url: "https://i.scdn.co/image/ab6761610000f178152cf48cf9541c7061570857",
            width: 160,
          },
        ],
        type: "artist",
        id: 768,
      },
    ],
    lastfmTagsNames: ["vinyl", "dads vinyl"],
    type: "album",
    markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CD",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IQ",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    lastfmTagsFull: [
      {
        name: "vinyl",
        url: "https://www.last.fm/tag/vinyl",
      },
      {
        name: "dads vinyl",
        url: "https://www.last.fm/tag/dads+vinyl",
      },
    ],
    id: 726,
  },
  id: 670,
  ludwigGenres: [
    {
      label: "rock-sub",
      confidence: 0.6229233145713806,
    },
    {
      label: "blues",
      confidence: 0.5229245713806,
    },
  ],
  ludwigMoods: [
    {
      label: "happy",
      confidence: 0.5654264092445374,
    },
    {
      label: "sad",
      confidence: 0.4210439920425415,
    },
    {
      label: "party",
      confidence: 0.3927437365055084,
    },
    {
      label: "relaxed",
      confidence: 0.5653913021087646,
    },
    {
      label: "acoustic",
      confidence: 0.6694174408912659,
    },
    {
      label: "electronic",
      confidence: 0.4021819829940796,
    },
    {
      label: "aggressive",
      confidence: 0.3527911901473999,
    },
  ],
  ludwigSubgenres: [
    {
      label: "rock---classic rock",
      confidence: 0.3049823045730591,
    },
    {
      label: "blues---electric blues",
      confidence: 0.3049823045730591,
    },
  ],
};

const trackFleet = {
  spotifyId: "07GvNcU1WdyZJq3XxP0kZa",
  spotifyUri: "spotify:track:07GvNcU1WdyZJq3XxP0kZa",
  spotifyAlbumId: "1bt6q2SruMsBtcerNVtpZB",
  name: "Go Your Own Way - 2004 Remaster",
  spotifyArtistsIds: ["08GQAI4eElDnROBrJRGE0X"],
  spotifyDurationMS: 223613,
  spotifyIsExplicit: false,
  spotifyIsPlayable: false,
  spotifyPreviewURL:
    "https://p.scdn.co/mp3-preview/eb79c81b8ad502f603124c24606cf81bf91cc98d?cid=7c4c757477e2485ea783355e72a900af",
  spotifyTrackAlbumPos: 5,
  spotifyDiscNumber: 1,
  spotifyUrl: "https://open.spotify.com/track/07GvNcU1WdyZJq3XxP0kZa",
  artists: [
    {
      name: "Fleetwood Mac",
      spotifyId: "08GQAI4eElDnROBrJRGE0X",
      spotifyUri: "spotify:artist:08GQAI4eElDnROBrJRGE0X",
      spotifyUrl: "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X",
      spotifyGenres: [
        "album rock",
        "classic rock",
        "mellow gold",
        "rock",
        "soft rock",
        "yacht rock",
      ],
      spotifyPopularity: 78,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb249d55f2d68a44637905c57e",
        "https://i.scdn.co/image/ab67616100005174249d55f2d68a44637905c57e",
        "https://i.scdn.co/image/ab6761610000f178249d55f2d68a44637905c57e",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb249d55f2d68a44637905c57e",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174249d55f2d68a44637905c57e",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178249d55f2d68a44637905c57e",
          width: 160,
        },
      ],
      type: "artist",
      id: 793,
    },
  ],
  genreVersion: 0,
  isSaved: false,
  spotifyPopularity: 76,
  type: "track",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TR",
    "TT",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  album: {
    spotifyId: "1bt6q2SruMsBtcerNVtpZB",
    name: "Rumours",
    spotifyCoverUrl: [
      "https://i.scdn.co/image/ab67616d0000b2730001af4f80be77069fc8fd41",
      "https://i.scdn.co/image/ab67616d00001e020001af4f80be77069fc8fd41",
      "https://i.scdn.co/image/ab67616d000048510001af4f80be77069fc8fd41",
    ],
    spotifyCovers: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b2730001af4f80be77069fc8fd41",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e020001af4f80be77069fc8fd41",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d000048510001af4f80be77069fc8fd41",
        width: 64,
      },
    ],
    spotifyUrl: "https://open.spotify.com/album/1bt6q2SruMsBtcerNVtpZB",
    spotifyReleaseDate: new Date("1977-02-03T23:00:00.000Z"),
    spotifyArtistsIds: ["08GQAI4eElDnROBrJRGE0X"],
    spotifyPopularity: 68,
    spotifyGenres: [],
    spotifyUri: "spotify:album:1bt6q2SruMsBtcerNVtpZB",
    albumTags: [],
    artists: [
      {
        name: "Fleetwood Mac",
        spotifyId: "08GQAI4eElDnROBrJRGE0X",
        spotifyUri: "spotify:artist:08GQAI4eElDnROBrJRGE0X",
        spotifyUrl: "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X",
        spotifyGenres: [
          "album rock",
          "classic rock",
          "mellow gold",
          "rock",
          "soft rock",
          "yacht rock",
        ],
        spotifyPopularity: 78,
        spotifyImgs: [
          "https://i.scdn.co/image/ab6761610000e5eb249d55f2d68a44637905c57e",
          "https://i.scdn.co/image/ab67616100005174249d55f2d68a44637905c57e",
          "https://i.scdn.co/image/ab6761610000f178249d55f2d68a44637905c57e",
        ],
        spotifyArtistImgs: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6761610000e5eb249d55f2d68a44637905c57e",
            width: 640,
          },
          {
            height: 320,
            url: "https://i.scdn.co/image/ab67616100005174249d55f2d68a44637905c57e",
            width: 320,
          },
          {
            height: 160,
            url: "https://i.scdn.co/image/ab6761610000f178249d55f2d68a44637905c57e",
            width: 160,
          },
        ],
        type: "artist",
        id: 793,
      },
    ],
    lastfmTagsNames: [
      "classic rock",
      "70s",
      "rock",
      "albums I own",
      "1977",
      "Fleetwood Mac",
      "soft rock",
      "favourite albums",
      "pop",
      "pop rock",
      "favorite albums",
      "1001 Albums You Must Hear Before You Die",
    ],
    type: "album",
    markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CD",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IQ",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TR",
      "TT",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    lastfmTagsFull: [
      {
        name: "classic rock",
        url: "https://www.last.fm/tag/classic+rock",
      },
      {
        name: "70s",
        url: "https://www.last.fm/tag/70s",
      },
      {
        name: "rock",
        url: "https://www.last.fm/tag/rock",
      },
      {
        name: "albums I own",
        url: "https://www.last.fm/tag/albums+I+own",
      },
      {
        name: "1977",
        url: "https://www.last.fm/tag/1977",
      },
      {
        name: "Fleetwood Mac",
        url: "https://www.last.fm/tag/Fleetwood+Mac",
      },
      {
        name: "soft rock",
        url: "https://www.last.fm/tag/soft+rock",
      },
      {
        name: "favourite albums",
        url: "https://www.last.fm/tag/favourite+albums",
      },
      {
        name: "pop",
        url: "https://www.last.fm/tag/pop",
      },
      {
        name: "pop rock",
        url: "https://www.last.fm/tag/pop+rock",
      },
      {
        name: "favorite albums",
        url: "https://www.last.fm/tag/favorite+albums",
      },
      {
        name: "1001 Albums You Must Hear Before You Die",
        url: "https://www.last.fm/tag/1001+Albums+You+Must+Hear+Before+You+Die",
      },
    ],
    id: 760,
  },
  id: 726,
  ludwigGenres: [
    {
      label: "rock-sub",
      confidence: 0.39742475748062134,
    },
  ],
  ludwigMoods: [
    {
      label: "happy",
      confidence: 0.7050925493240356,
    },
    {
      label: "sad",
      confidence: 0.05775046348571777,
    },
    {
      label: "party",
      confidence: 0.7238423824310303,
    },
    {
      label: "relaxed",
      confidence: 0.13228708505630493,
    },
    {
      label: "acoustic",
      confidence: 0.16137240827083588,
    },
    {
      label: "electronic",
      confidence: 0.40132683515548706,
    },
    {
      label: "aggressive",
      confidence: 0.8673527836799622,
    },
  ],
  ludwigSubgenres: [
    {
      label: "rock---classic rock",
      confidence: 0.392123818397522,
    },
  ],
};

const trackBeat = {
  spotifyId: "18AXbzPzBS8Y3AkgSxzJPb",
  spotifyUri: "spotify:track:18AXbzPzBS8Y3AkgSxzJPb",
  spotifyAlbumId: "1cM3r0WQZWNkCpEbmFjLln",
  name: "In The Air Tonight - 2015 Remastered",
  spotifyArtistsIds: ["4lxfqrEsLX6N1N4OCSkILp"],
  spotifyDurationMS: 336453,
  spotifyIsExplicit: false,
  spotifyIsPlayable: false,
  spotifyPreviewURL:
    "https://p.scdn.co/mp3-preview/be4a5765f51d84975c2864587a1727d13fb81061?cid=7c4c757477e2485ea783355e72a900af",
  spotifyTrackAlbumPos: 1,
  spotifyDiscNumber: 1,
  spotifyUrl: "https://open.spotify.com/track/18AXbzPzBS8Y3AkgSxzJPb",
  artists: [
    {
      name: "Phil Collins",
      spotifyId: "4lxfqrEsLX6N1N4OCSkILp",
      spotifyUri: "spotify:artist:4lxfqrEsLX6N1N4OCSkILp",
      spotifyUrl: "https://open.spotify.com/artist/4lxfqrEsLX6N1N4OCSkILp",
      spotifyGenres: ["mellow gold", "rock drums", "soft rock"],
      spotifyPopularity: 74,
      spotifyImgs: [
        "https://i.scdn.co/image/31fbe64783eb5d493161640bd599dceafc615c6d",
        "https://i.scdn.co/image/f5b1b588936c53348efe5526caf65852a0bd1d36",
        "https://i.scdn.co/image/ccd188b7082ce425d61640c11ea715d23dbce92a",
        "https://i.scdn.co/image/7900732380c7303c222bc98f68e1b9fba3922439",
      ],
      spotifyArtistImgs: [
        {
          height: 1333,
          url: "https://i.scdn.co/image/31fbe64783eb5d493161640bd599dceafc615c6d",
          width: 1000,
        },
        {
          height: 853,
          url: "https://i.scdn.co/image/f5b1b588936c53348efe5526caf65852a0bd1d36",
          width: 640,
        },
        {
          height: 267,
          url: "https://i.scdn.co/image/ccd188b7082ce425d61640c11ea715d23dbce92a",
          width: 200,
        },
        {
          height: 85,
          url: "https://i.scdn.co/image/7900732380c7303c222bc98f68e1b9fba3922439",
          width: 64,
        },
      ],
      type: "artist",
      id: 863,
    },
  ],
  genreVersion: 0,
  isSaved: false,
  spotifyPopularity: 77,
  type: "track",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  album: {
    spotifyId: "1cM3r0WQZWNkCpEbmFjLln",
    name: "Face Value (Deluxe Editon)",
    spotifyCoverUrl: [
      "https://i.scdn.co/image/ab67616d0000b273f6954c1f074f66907a8c5483",
      "https://i.scdn.co/image/ab67616d00001e02f6954c1f074f66907a8c5483",
      "https://i.scdn.co/image/ab67616d00004851f6954c1f074f66907a8c5483",
    ],
    spotifyCovers: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273f6954c1f074f66907a8c5483",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02f6954c1f074f66907a8c5483",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851f6954c1f074f66907a8c5483",
        width: 64,
      },
    ],
    spotifyUrl: "https://open.spotify.com/album/1cM3r0WQZWNkCpEbmFjLln",
    spotifyReleaseDate: new Date("1980-12-31T23:00:00.000Z"),
    spotifyArtistsIds: ["4lxfqrEsLX6N1N4OCSkILp"],
    spotifyPopularity: 62,
    spotifyGenres: [],
    spotifyUri: "spotify:album:1cM3r0WQZWNkCpEbmFjLln",
    albumTags: [],
    artists: [
      {
        name: "Phil Collins",
        spotifyId: "4lxfqrEsLX6N1N4OCSkILp",
        spotifyUri: "spotify:artist:4lxfqrEsLX6N1N4OCSkILp",
        spotifyUrl: "https://open.spotify.com/artist/4lxfqrEsLX6N1N4OCSkILp",
        spotifyGenres: ["mellow gold", "rock drums", "soft rock"],
        spotifyPopularity: 74,
        spotifyImgs: [
          "https://i.scdn.co/image/31fbe64783eb5d493161640bd599dceafc615c6d",
          "https://i.scdn.co/image/f5b1b588936c53348efe5526caf65852a0bd1d36",
          "https://i.scdn.co/image/ccd188b7082ce425d61640c11ea715d23dbce92a",
          "https://i.scdn.co/image/7900732380c7303c222bc98f68e1b9fba3922439",
        ],
        spotifyArtistImgs: [
          {
            height: 1333,
            url: "https://i.scdn.co/image/31fbe64783eb5d493161640bd599dceafc615c6d",
            width: 1000,
          },
          {
            height: 853,
            url: "https://i.scdn.co/image/f5b1b588936c53348efe5526caf65852a0bd1d36",
            width: 640,
          },
          {
            height: 267,
            url: "https://i.scdn.co/image/ccd188b7082ce425d61640c11ea715d23dbce92a",
            width: 200,
          },
          {
            height: 85,
            url: "https://i.scdn.co/image/7900732380c7303c222bc98f68e1b9fba3922439",
            width: 64,
          },
        ],
        type: "artist",
        id: 863,
      },
    ],
    lastfmTagsNames: ["soft rock"],
    type: "album",
    markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CD",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IQ",
      "IS",
      "IT",
      "JM",
      "JO",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    lastfmTagsFull: [
      {
        name: "soft rock",
        url: "https://www.last.fm/tag/soft+rock",
      },
    ],
    id: 840,
  },
  id: 800,
  ludwigGenres: [
    {
      label: "rock-sub",
      confidence: 0.4958716154098511,
    },
  ],
  ludwigMoods: [
    {
      label: "happy",
      confidence: 0.4018964171409607,
    },
    {
      label: "sad",
      confidence: 0.5851744413375854,
    },
    {
      label: "party",
      confidence: 0.25920212268829346,
    },
    {
      label: "relaxed",
      confidence: 0.7115442156791687,
    },
    {
      label: "acoustic",
      confidence: 0.611219048500061,
    },
    {
      label: "electronic",
      confidence: 0.4672262370586395,
    },
    {
      label: "aggressive",
      confidence: 0.2609504461288452,
    },
  ],
  ludwigSubgenres: [
    {
      label: "rock---progressive",
      confidence: 0.46698248386383057,
    },
  ],
};

const trackPearl = {
  spotifyId: "5Xak5fmy089t0FYmh3VJiY",
  spotifyUri: "spotify:track:5Xak5fmy089t0FYmh3VJiY",
  spotifyAlbumId: "5B4PYA7wNN4WdEXdIJu58a",
  name: "Black",
  spotifyArtistsIds: ["1w5Kfo2jwwIPruYS2UWh56"],
  spotifyDurationMS: 342653,
  spotifyIsExplicit: false,
  spotifyIsPlayable: false,
  spotifyPreviewURL:
    "https://p.scdn.co/mp3-preview/0d90906ce8999a0313553bcb6f026c8425a4df39?cid=7c4c757477e2485ea783355e72a900af",
  spotifyTrackAlbumPos: 5,
  spotifyDiscNumber: 1,
  spotifyUrl: "https://open.spotify.com/track/5Xak5fmy089t0FYmh3VJiY",
  artists: [
    {
      name: "Pearl Jam",
      spotifyId: "1w5Kfo2jwwIPruYS2UWh56",
      spotifyUri: "spotify:artist:1w5Kfo2jwwIPruYS2UWh56",
      spotifyUrl: "https://open.spotify.com/artist/1w5Kfo2jwwIPruYS2UWh56",
      spotifyGenres: ["grunge", "permanent wave", "rock"],
      spotifyPopularity: 73,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb122d1145d880736383742ebc",
        "https://i.scdn.co/image/ab67616100005174122d1145d880736383742ebc",
        "https://i.scdn.co/image/ab6761610000f178122d1145d880736383742ebc",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb122d1145d880736383742ebc",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174122d1145d880736383742ebc",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178122d1145d880736383742ebc",
          width: 160,
        },
      ],
      type: "artist",
      id: 684,
    },
  ],
  genreVersion: 0,
  isSaved: false,
  spotifyPopularity: 73,
  type: "track",
  markets: [
    "AD",
    "AE",
    "AR",
    "AT",
    "AU",
    "BE",
    "BG",
    "BH",
    "BO",
    "BR",
    "CA",
    "CH",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DE",
    "DK",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FR",
    "GB",
    "GR",
    "GT",
    "HK",
    "HN",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JO",
    "JP",
    "KW",
    "LB",
    "LI",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MT",
    "MX",
    "MY",
    "NI",
    "NL",
    "NO",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PH",
    "PL",
    "PS",
    "PT",
    "PY",
    "QA",
    "RO",
    "SA",
    "SE",
    "SG",
    "SK",
    "SV",
    "TH",
    "TN",
    "TR",
    "TW",
    "US",
    "UY",
    "VN",
    "ZA",
  ],
  album: {
    spotifyId: "5B4PYA7wNN4WdEXdIJu58a",
    name: "Ten",
    spotifyCoverUrl: [
      "https://i.scdn.co/image/ab67616d0000b273d400d27cba05bb0545533864",
      "https://i.scdn.co/image/ab67616d00001e02d400d27cba05bb0545533864",
      "https://i.scdn.co/image/ab67616d00004851d400d27cba05bb0545533864",
    ],
    spotifyCovers: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273d400d27cba05bb0545533864",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02d400d27cba05bb0545533864",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851d400d27cba05bb0545533864",
        width: 64,
      },
    ],
    spotifyUrl: "https://open.spotify.com/album/5B4PYA7wNN4WdEXdIJu58a",
    spotifyReleaseDate: new Date("1991-08-26T22:00:00.000Z"),
    spotifyArtistsIds: ["1w5Kfo2jwwIPruYS2UWh56"],
    spotifyPopularity: 70,
    spotifyGenres: [],
    spotifyUri: "spotify:album:5B4PYA7wNN4WdEXdIJu58a",
    albumTags: [],
    artists: [
      {
        name: "Pearl Jam",
        spotifyId: "1w5Kfo2jwwIPruYS2UWh56",
        spotifyUri: "spotify:artist:1w5Kfo2jwwIPruYS2UWh56",
        spotifyUrl: "https://open.spotify.com/artist/1w5Kfo2jwwIPruYS2UWh56",
        spotifyGenres: ["grunge", "permanent wave", "rock"],
        spotifyPopularity: 73,
        spotifyImgs: [
          "https://i.scdn.co/image/ab6761610000e5eb122d1145d880736383742ebc",
          "https://i.scdn.co/image/ab67616100005174122d1145d880736383742ebc",
          "https://i.scdn.co/image/ab6761610000f178122d1145d880736383742ebc",
        ],
        spotifyArtistImgs: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6761610000e5eb122d1145d880736383742ebc",
            width: 640,
          },
          {
            height: 320,
            url: "https://i.scdn.co/image/ab67616100005174122d1145d880736383742ebc",
            width: 320,
          },
          {
            height: 160,
            url: "https://i.scdn.co/image/ab6761610000f178122d1145d880736383742ebc",
            width: 160,
          },
        ],
        type: "artist",
        id: 684,
      },
    ],
    lastfmTagsNames: [
      "Grunge",
      "albums I own",
      "rock",
      "alternative rock",
      "90s",
      "favorite albums",
      "1991",
      "alternative",
      "favourite albums",
      "pearl jam",
      "hard rock",
      "seattle",
    ],
    type: "album",
    markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CD",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IQ",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    lastfmTagsFull: [
      {
        name: "Grunge",
        url: "https://www.last.fm/tag/Grunge",
      },
      {
        name: "albums I own",
        url: "https://www.last.fm/tag/albums+I+own",
      },
      {
        name: "rock",
        url: "https://www.last.fm/tag/rock",
      },
      {
        name: "alternative rock",
        url: "https://www.last.fm/tag/alternative+rock",
      },
      {
        name: "90s",
        url: "https://www.last.fm/tag/90s",
      },
      {
        name: "favorite albums",
        url: "https://www.last.fm/tag/favorite+albums",
      },
      {
        name: "1991",
        url: "https://www.last.fm/tag/1991",
      },
      {
        name: "alternative",
        url: "https://www.last.fm/tag/alternative",
      },
      {
        name: "favourite albums",
        url: "https://www.last.fm/tag/favourite+albums",
      },
      {
        name: "pearl jam",
        url: "https://www.last.fm/tag/pearl+jam",
      },
      {
        name: "hard rock",
        url: "https://www.last.fm/tag/hard+rock",
      },
      {
        name: "seattle",
        url: "https://www.last.fm/tag/seattle",
      },
    ],
    id: 652,
  },
  id: 562,
  ludwigGenres: [
    {
      label: "rock-sub",
      confidence: 0.6808691024780273,
    },
  ],
  ludwigMoods: [
    {
      label: "happy",
      confidence: 0.7243837714195251,
    },
    {
      label: "sad",
      confidence: 0.12042658776044846,
    },
    {
      label: "party",
      confidence: 0.5324057340621948,
    },
    {
      label: "relaxed",
      confidence: 0.2981046736240387,
    },
    {
      label: "acoustic",
      confidence: 0.2569902837276459,
    },
    {
      label: "electronic",
      confidence: 0.3701913356781006,
    },
    {
      label: "aggressive",
      confidence: 0.6840365529060364,
    },
  ],
  ludwigSubgenres: [
    {
      label: "rock---pop rock",
      confidence: 0.3029489815235138,
    },
    {
      label: "rock---grunge",
      confidence: 0.6029489815235138,
    },
  ],
};

const trackDaft = {
  spotifyId: "2LD2gT7gwAurzdQDQtILds",
  spotifyUri: "spotify:track:2LD2gT7gwAurzdQDQtILds",
  spotifyAlbumId: "2noRn2Aes5aoNVsU6iWThc",
  name: "Veridis Quo",
  spotifyArtistsIds: ["4tZwfgrHOc3mvqYlEYSvVi"],
  spotifyDurationMS: 345186,
  spotifyIsExplicit: false,
  spotifyIsPlayable: false,
  spotifyPreviewURL:
    "https://p.scdn.co/mp3-preview/6eca9543a05607263bfc48413ff16f5f9aae7d40?cid=7c4c757477e2485ea783355e72a900af",
  spotifyTrackAlbumPos: 11,
  spotifyDiscNumber: 1,
  spotifyUrl: "https://open.spotify.com/track/2LD2gT7gwAurzdQDQtILds",
  artists: [
    {
      name: "Daft Punk",
      spotifyId: "4tZwfgrHOc3mvqYlEYSvVi",
      spotifyUri: "spotify:artist:4tZwfgrHOc3mvqYlEYSvVi",
      spotifyUrl: "https://open.spotify.com/artist/4tZwfgrHOc3mvqYlEYSvVi",
      spotifyGenres: ["electro", "filter house"],
      spotifyPopularity: 78,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb96d66c60658005885d1135ce",
        "https://i.scdn.co/image/ab6761610000517496d66c60658005885d1135ce",
        "https://i.scdn.co/image/ab6761610000f17896d66c60658005885d1135ce",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb96d66c60658005885d1135ce",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab6761610000517496d66c60658005885d1135ce",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f17896d66c60658005885d1135ce",
          width: 160,
        },
      ],
      type: "artist",
      id: 696,
    },
  ],
  genreVersion: 0,
  isSaved: false,
  spotifyPopularity: 66,
  type: "track",
  markets: [
    "AD",
    "AE",
    "AR",
    "AT",
    "AU",
    "BE",
    "BG",
    "BH",
    "BO",
    "BR",
    "CA",
    "CH",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DE",
    "DK",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FR",
    "GB",
    "GR",
    "GT",
    "HK",
    "HN",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JO",
    "JP",
    "KW",
    "LB",
    "LI",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MT",
    "MX",
    "MY",
    "NI",
    "NL",
    "NO",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PH",
    "PL",
    "PS",
    "PT",
    "PY",
    "QA",
    "RO",
    "SA",
    "SE",
    "SG",
    "SK",
    "SV",
    "TH",
    "TN",
    "TR",
    "TW",
    "US",
    "UY",
    "VN",
    "ZA",
  ],
  album: {
    spotifyId: "2noRn2Aes5aoNVsU6iWThc",
    name: "Discovery",
    spotifyCoverUrl: [
      "https://i.scdn.co/image/ab67616d0000b273b33d46dfa2635a47eebf63b2",
      "https://i.scdn.co/image/ab67616d00001e02b33d46dfa2635a47eebf63b2",
      "https://i.scdn.co/image/ab67616d00004851b33d46dfa2635a47eebf63b2",
    ],
    spotifyCovers: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273b33d46dfa2635a47eebf63b2",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02b33d46dfa2635a47eebf63b2",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851b33d46dfa2635a47eebf63b2",
        width: 64,
      },
    ],
    spotifyUrl: "https://open.spotify.com/album/2noRn2Aes5aoNVsU6iWThc",
    spotifyReleaseDate: new Date("2001-03-11T23:00:00.000Z"),
    spotifyArtistsIds: ["4tZwfgrHOc3mvqYlEYSvVi"],
    spotifyPopularity: 69,
    spotifyGenres: [],
    spotifyUri: "spotify:album:2noRn2Aes5aoNVsU6iWThc",
    albumTags: [],
    artists: [
      {
        name: "Daft Punk",
        spotifyId: "4tZwfgrHOc3mvqYlEYSvVi",
        spotifyUri: "spotify:artist:4tZwfgrHOc3mvqYlEYSvVi",
        spotifyUrl: "https://open.spotify.com/artist/4tZwfgrHOc3mvqYlEYSvVi",
        spotifyGenres: ["electro", "filter house"],
        spotifyPopularity: 78,
        spotifyImgs: [
          "https://i.scdn.co/image/ab6761610000e5eb96d66c60658005885d1135ce",
          "https://i.scdn.co/image/ab6761610000517496d66c60658005885d1135ce",
          "https://i.scdn.co/image/ab6761610000f17896d66c60658005885d1135ce",
        ],
        spotifyArtistImgs: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6761610000e5eb96d66c60658005885d1135ce",
            width: 640,
          },
          {
            height: 320,
            url: "https://i.scdn.co/image/ab6761610000517496d66c60658005885d1135ce",
            width: 320,
          },
          {
            height: 160,
            url: "https://i.scdn.co/image/ab6761610000f17896d66c60658005885d1135ce",
            width: 160,
          },
        ],
        type: "artist",
        id: 696,
      },
    ],
    lastfmTagsNames: [
      "electronic",
      "House",
      "albums I own",
      "dance",
      "electronica",
      "2001",
      "french",
      "favourite albums",
      "french house",
      "Daft Punk",
      "techno",
      "favorite albums",
    ],
    type: "album",
    markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CD",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IQ",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    lastfmTagsFull: [
      {
        name: "electronic",
        url: "https://www.last.fm/tag/electronic",
      },
      {
        name: "House",
        url: "https://www.last.fm/tag/House",
      },
      {
        name: "albums I own",
        url: "https://www.last.fm/tag/albums+I+own",
      },
      {
        name: "dance",
        url: "https://www.last.fm/tag/dance",
      },
      {
        name: "electronica",
        url: "https://www.last.fm/tag/electronica",
      },
      {
        name: "2001",
        url: "https://www.last.fm/tag/2001",
      },
      {
        name: "french",
        url: "https://www.last.fm/tag/french",
      },
      {
        name: "favourite albums",
        url: "https://www.last.fm/tag/favourite+albums",
      },
      {
        name: "french house",
        url: "https://www.last.fm/tag/french+house",
      },
      {
        name: "Daft Punk",
        url: "https://www.last.fm/tag/Daft+Punk",
      },
      {
        name: "techno",
        url: "https://www.last.fm/tag/techno",
      },
      {
        name: "favorite albums",
        url: "https://www.last.fm/tag/favorite+albums",
      },
    ],
    id: 664,
  },
  id: 598,
  ludwigGenres: [
    {
      label: "funk / soul",
      confidence: 0.515007495880127,
    },
    {
      label: "electronic",
      confidence: 0.715007495880127,
    },
  ],
  ludwigMoods: [
    {
      label: "happy",
      confidence: 0.4053296744823456,
    },
    {
      label: "sad",
      confidence: 0.705848217010498,
    },
    {
      label: "party",
      confidence: 0.294009268283844,
    },
    {
      label: "relaxed",
      confidence: 0.8010265827178955,
    },
    {
      label: "acoustic",
      confidence: 0.7802526950836182,
    },
    {
      label: "electronic",
      confidence: 0.6727265119552612,
    },
    {
      label: "aggressive",
      confidence: 0.214713916182518,
    },
  ],
  ludwigSubgenres: [
    {
      label: "funk / soul---rhythm & blues",
      confidence: 0.40325602889060974,
    },
    {
      label: "funk / soul---soul",
      confidence: 0.6533706784248352,
    },
    {
      label: "electronic---house",
      confidence: 0.6533706784248352,
    },

  ],
};

// @ts-ignore
const demoTracks: Track[] = shuffle([
  trackBeat,
  trackBowie,
  trackCash,
  trackDaft,
  trackMich,
  trackMine,
  trackPearl,
  trackFleet,
]);

export default demoTracks;
