import { Album } from "data/cacheDB/dexieDB/models/Album";
import { shuffle } from "lodash";

const albumMantle = {
  spotifyId: "7hOOJDRbH3we1P0iT2z1Hg",
  name: "The Mantle",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273ac5a3d24a0d86ac8d838bd47",
    "https://i.scdn.co/image/ab67616d00001e02ac5a3d24a0d86ac8d838bd47",
    "https://i.scdn.co/image/ab67616d00004851ac5a3d24a0d86ac8d838bd47",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273ac5a3d24a0d86ac8d838bd47",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02ac5a3d24a0d86ac8d838bd47",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851ac5a3d24a0d86ac8d838bd47",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/7hOOJDRbH3we1P0iT2z1Hg",
  spotifyReleaseDate: new Date("2001-12-31T23:00:00.000Z"),
  spotifyArtistsIds: ["3Meu28o8P5z9Zjm6NTGihT"],
  spotifyPopularity: 33,
  spotifyGenres: [],
  spotifyUri: "spotify:album:7hOOJDRbH3we1P0iT2z1Hg",
  albumTags: [],
  artists: [
    {
      name: "Agalloch",
      spotifyId: "3Meu28o8P5z9Zjm6NTGihT",
      spotifyUri: "spotify:artist:3Meu28o8P5z9Zjm6NTGihT",
      spotifyUrl: "https://open.spotify.com/artist/3Meu28o8P5z9Zjm6NTGihT",
      spotifyGenres: [
        "atmospheric black metal",
        "atmospheric doom",
        "black metal",
        "blackgaze",
        "cascadian black metal",
        "doom metal",
        "pagan black metal",
        "portland metal",
        "post-metal",
        "usbm",
        "voidgaze",
      ],
      spotifyPopularity: 37,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5ebea06e6637a861aba6cba7e58",
        "https://i.scdn.co/image/ab67616100005174ea06e6637a861aba6cba7e58",
        "https://i.scdn.co/image/ab6761610000f178ea06e6637a861aba6cba7e58",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebea06e6637a861aba6cba7e58",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174ea06e6637a861aba6cba7e58",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178ea06e6637a861aba6cba7e58",
          width: 160,
        },
      ],
      type: "artist",
      id: 978,
    },
  ],
  lastfmTagsNames: [
    "folk metal",
    "doom metal",
    "black metal",
    "2002",
    "albums I own",
    "Progressive metal",
    "favourite albums",
    "favorite albums",
    "misanthropic gay romance nostalgia metal",
    "melodic diarrhea metal",
    "vomit-inducing homoerotic black metal",
    "progressive neo-erotic frottage metal influenced by pictures of gay elks having buttsecks in the snow",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "folk metal",
      url: "https://www.last.fm/tag/folk+metal",
    },
    {
      name: "doom metal",
      url: "https://www.last.fm/tag/doom+metal",
    },
    {
      name: "black metal",
      url: "https://www.last.fm/tag/black+metal",
    },
    {
      name: "2002",
      url: "https://www.last.fm/tag/2002",
    },
    {
      name: "albums I own",
      url: "https://www.last.fm/tag/albums+I+own",
    },
    {
      name: "Progressive metal",
      url: "https://www.last.fm/tag/Progressive+metal",
    },
    {
      name: "favourite albums",
      url: "https://www.last.fm/tag/favourite+albums",
    },
    {
      name: "favorite albums",
      url: "https://www.last.fm/tag/favorite+albums",
    },
    {
      name: "misanthropic gay romance nostalgia metal",
      url: "https://www.last.fm/tag/misanthropic+gay+romance+nostalgia+metal",
    },
    {
      name: "melodic diarrhea metal",
      url: "https://www.last.fm/tag/melodic+diarrhea+metal",
    },
    {
      name: "vomit-inducing homoerotic black metal",
      url: "https://www.last.fm/tag/vomit-inducing+homoerotic+black+metal",
    },
    {
      name: "progressive neo-erotic frottage metal influenced by pictures of gay elks having buttsecks in the snow",
      url: "https://www.last.fm/tag/progressive+neo-erotic+frottage+metal+influenced+by+pictures+of+gay+elks+having+buttsecks+in+the+snow",
    },
  ],
  id: 939,
};

const albumDynamo = {
  spotifyId: "4bfwXuecOmNVlPM5RStAiQ",
  name: "Dynamo (Remastered)",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273b755f1b1b4410d404fe21167",
    "https://i.scdn.co/image/ab67616d00001e02b755f1b1b4410d404fe21167",
    "https://i.scdn.co/image/ab67616d00004851b755f1b1b4410d404fe21167",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273b755f1b1b4410d404fe21167",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02b755f1b1b4410d404fe21167",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851b755f1b1b4410d404fe21167",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/4bfwXuecOmNVlPM5RStAiQ",
  spotifyReleaseDate: new Date("1992-10-08T23:00:00.000Z"),
  spotifyArtistsIds: ["7An4yvF7hDYDolN4m5zKBp"],
  spotifyPopularity: 48,
  spotifyGenres: [],
  spotifyUri: "spotify:album:4bfwXuecOmNVlPM5RStAiQ",
  albumTags: [],
  artists: [
    {
      name: "Soda Stereo",
      spotifyId: "7An4yvF7hDYDolN4m5zKBp",
      spotifyUri: "spotify:artist:7An4yvF7hDYDolN4m5zKBp",
      spotifyUrl: "https://open.spotify.com/artist/7An4yvF7hDYDolN4m5zKBp",
      spotifyGenres: [
        "argentine rock",
        "latin alternative",
        "latin rock",
        "post-punk argentina",
        "rock en espanol",
        "ska argentino",
      ],
      spotifyPopularity: 71,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb4a6d2f5e161c011cdb9cef69",
        "https://i.scdn.co/image/ab676161000051744a6d2f5e161c011cdb9cef69",
        "https://i.scdn.co/image/ab6761610000f1784a6d2f5e161c011cdb9cef69",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb4a6d2f5e161c011cdb9cef69",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051744a6d2f5e161c011cdb9cef69",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1784a6d2f5e161c011cdb9cef69",
          width: 160,
        },
      ],
      type: "artist",
      id: 991,
    },
  ],
  lastfmTagsNames: ["shoegaze", "1992", "favourite albums"],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "shoegaze",
      url: "https://www.last.fm/tag/shoegaze",
    },
    {
      name: "1992",
      url: "https://www.last.fm/tag/1992",
    },
    {
      name: "favourite albums",
      url: "https://www.last.fm/tag/favourite+albums",
    },
  ],
  id: 954,
};

const albumGlow = {
  spotifyId: "6QYoRO2sXThCORAifrP4Bl",
  name: "The Glow, Pt. 2",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b27300c91ccec6800014b8513717",
    "https://i.scdn.co/image/ab67616d00001e0200c91ccec6800014b8513717",
    "https://i.scdn.co/image/ab67616d0000485100c91ccec6800014b8513717",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b27300c91ccec6800014b8513717",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e0200c91ccec6800014b8513717",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d0000485100c91ccec6800014b8513717",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/6QYoRO2sXThCORAifrP4Bl",
  spotifyReleaseDate: new Date("2001-09-10T22:00:00.000Z"),
  spotifyArtistsIds: ["7Ht57YadlBXcFJDK3plmhO"],
  spotifyPopularity: 46,
  spotifyGenres: [],
  spotifyUri: "spotify:album:6QYoRO2sXThCORAifrP4Bl",
  albumTags: [],
  artists: [
    {
      name: "The Microphones",
      spotifyId: "7Ht57YadlBXcFJDK3plmhO",
      spotifyUri: "spotify:artist:7Ht57YadlBXcFJDK3plmhO",
      spotifyUrl: "https://open.spotify.com/artist/7Ht57YadlBXcFJDK3plmhO",
      spotifyGenres: [
        "alternative rock",
        "anti-folk",
        "experimental rock",
        "indie rock",
        "lo-fi",
        "lo-fi indie",
        "noise pop",
        "olympia wa indie",
      ],
      spotifyPopularity: 44,
      spotifyImgs: [
        "https://i.scdn.co/image/866667893c025a6bc6ae4e6e9a79f57c54f65429",
        "https://i.scdn.co/image/1030acea742d47a7b12fc7da1d4e14328a9a4635",
        "https://i.scdn.co/image/5ebf004da94e4e82a21a295137d1f158469b56fb",
        "https://i.scdn.co/image/234d3be762aa318f1dfe14d875ca2c40e521a779",
      ],
      spotifyArtistImgs: [
        {
          height: 698,
          url: "https://i.scdn.co/image/866667893c025a6bc6ae4e6e9a79f57c54f65429",
          width: 1000,
        },
        {
          height: 446,
          url: "https://i.scdn.co/image/1030acea742d47a7b12fc7da1d4e14328a9a4635",
          width: 639,
        },
        {
          height: 140,
          url: "https://i.scdn.co/image/5ebf004da94e4e82a21a295137d1f158469b56fb",
          width: 200,
        },
        {
          height: 45,
          url: "https://i.scdn.co/image/234d3be762aa318f1dfe14d875ca2c40e521a779",
          width: 64,
        },
      ],
      type: "artist",
      id: 1010,
    },
  ],
  lastfmTagsNames: [
    "indie folk",
    "2001",
    "folk",
    "Lo-Fi",
    "psychedelic folk",
    "favorite albums",
    "Lo-Fi Indie",
    "experimental",
    "indie rock",
    "noise rock",
    "indie",
    "pop",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "indie folk",
      url: "https://www.last.fm/tag/indie+folk",
    },
    {
      name: "2001",
      url: "https://www.last.fm/tag/2001",
    },
    {
      name: "folk",
      url: "https://www.last.fm/tag/folk",
    },
    {
      name: "Lo-Fi",
      url: "https://www.last.fm/tag/Lo-Fi",
    },
    {
      name: "psychedelic folk",
      url: "https://www.last.fm/tag/psychedelic+folk",
    },
    {
      name: "favorite albums",
      url: "https://www.last.fm/tag/favorite+albums",
    },
    {
      name: "Lo-Fi Indie",
      url: "https://www.last.fm/tag/Lo-Fi+Indie",
    },
    {
      name: "experimental",
      url: "https://www.last.fm/tag/experimental",
    },
    {
      name: "indie rock",
      url: "https://www.last.fm/tag/indie+rock",
    },
    {
      name: "noise rock",
      url: "https://www.last.fm/tag/noise+rock",
    },
    {
      name: "indie",
      url: "https://www.last.fm/tag/indie",
    },
    {
      name: "pop",
      url: "https://www.last.fm/tag/pop",
    },
  ],
  id: 970,
};

const albumBad = {
  spotifyId: "5lJqux7orBlA1QzyiBGti1",
  name: "YHLQMDLG",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273548f7ec52da7313de0c5e4a0",
    "https://i.scdn.co/image/ab67616d00001e02548f7ec52da7313de0c5e4a0",
    "https://i.scdn.co/image/ab67616d00004851548f7ec52da7313de0c5e4a0",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273548f7ec52da7313de0c5e4a0",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02548f7ec52da7313de0c5e4a0",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851548f7ec52da7313de0c5e4a0",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/5lJqux7orBlA1QzyiBGti1",
  spotifyReleaseDate: new Date("2020-02-28T23:00:00.000Z"),
  spotifyArtistsIds: ["4q3ewBCX7sLwd24euuV69X"],
  spotifyPopularity: 84,
  spotifyGenres: [],
  spotifyUri: "spotify:album:5lJqux7orBlA1QzyiBGti1",
  albumTags: [],
  artists: [
    {
      name: "Bad Bunny",
      spotifyId: "4q3ewBCX7sLwd24euuV69X",
      spotifyUri: "spotify:artist:4q3ewBCX7sLwd24euuV69X",
      spotifyUrl: "https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X",
      spotifyGenres: ["latin", "reggaeton", "trap latino"],
      spotifyPopularity: 100,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb8ee9a6f54dcbd4bc95126b14",
        "https://i.scdn.co/image/ab676161000051748ee9a6f54dcbd4bc95126b14",
        "https://i.scdn.co/image/ab6761610000f1788ee9a6f54dcbd4bc95126b14",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb8ee9a6f54dcbd4bc95126b14",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051748ee9a6f54dcbd4bc95126b14",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1788ee9a6f54dcbd4bc95126b14",
          width: 160,
        },
      ],
      type: "artist",
      id: 1023,
    },
  ],
  lastfmTagsNames: [
    "2020",
    "trap",
    "Latin Trap",
    "indie",
    "Reggaeton",
    "rnb",
    "latin pop",
    "bad bunny",
    "trap latino",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "2020",
      url: "https://www.last.fm/tag/2020",
    },
    {
      name: "trap",
      url: "https://www.last.fm/tag/trap",
    },
    {
      name: "Latin Trap",
      url: "https://www.last.fm/tag/Latin+Trap",
    },
    {
      name: "indie",
      url: "https://www.last.fm/tag/indie",
    },
    {
      name: "Reggaeton",
      url: "https://www.last.fm/tag/Reggaeton",
    },
    {
      name: "rnb",
      url: "https://www.last.fm/tag/rnb",
    },
    {
      name: "latin pop",
      url: "https://www.last.fm/tag/latin+pop",
    },
    {
      name: "bad bunny",
      url: "https://www.last.fm/tag/bad+bunny",
    },
    {
      name: "trap latino",
      url: "https://www.last.fm/tag/trap+latino",
    },
  ],
  id: 985,
};

const albumLateralus = {
  spotifyId: "5l5m1hnH4punS1GQXgEi3T",
  name: "Lateralus",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273ca41a947c13b78749c4953b1",
    "https://i.scdn.co/image/ab67616d00001e02ca41a947c13b78749c4953b1",
    "https://i.scdn.co/image/ab67616d00004851ca41a947c13b78749c4953b1",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273ca41a947c13b78749c4953b1",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02ca41a947c13b78749c4953b1",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851ca41a947c13b78749c4953b1",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/5l5m1hnH4punS1GQXgEi3T",
  spotifyReleaseDate: new Date("2001-05-14T22:00:00.000Z"),
  spotifyArtistsIds: ["2yEwvVSSSUkcLeSTNyHKh8"],
  spotifyPopularity: 62,
  spotifyGenres: [],
  spotifyUri: "spotify:album:5l5m1hnH4punS1GQXgEi3T",
  albumTags: [],
  artists: [
    {
      name: "TOOL",
      spotifyId: "2yEwvVSSSUkcLeSTNyHKh8",
      spotifyUri: "spotify:artist:2yEwvVSSSUkcLeSTNyHKh8",
      spotifyUrl: "https://open.spotify.com/artist/2yEwvVSSSUkcLeSTNyHKh8",
      spotifyGenres: [
        "alternative metal",
        "alternative rock",
        "art rock",
        "nu metal",
        "progressive metal",
        "progressive rock",
        "rock",
      ],
      spotifyPopularity: 69,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb13f5472b709101616c87cba3",
        "https://i.scdn.co/image/ab6761610000517413f5472b709101616c87cba3",
        "https://i.scdn.co/image/ab6761610000f17813f5472b709101616c87cba3",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb13f5472b709101616c87cba3",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab6761610000517413f5472b709101616c87cba3",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f17813f5472b709101616c87cba3",
          width: 160,
        },
      ],
      type: "artist",
      id: 1031,
    },
  ],
  lastfmTagsNames: [
    "albums I own",
    "Progressive metal",
    "Progressive rock",
    "favourite albums",
    "metal",
    "2001",
    "favorite albums",
    "alternative metal",
    "tool",
    "rock",
    "Masterpiece",
    "alternative",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "albums I own",
      url: "https://www.last.fm/tag/albums+I+own",
    },
    {
      name: "Progressive metal",
      url: "https://www.last.fm/tag/Progressive+metal",
    },
    {
      name: "Progressive rock",
      url: "https://www.last.fm/tag/Progressive+rock",
    },
    {
      name: "favourite albums",
      url: "https://www.last.fm/tag/favourite+albums",
    },
    {
      name: "metal",
      url: "https://www.last.fm/tag/metal",
    },
    {
      name: "2001",
      url: "https://www.last.fm/tag/2001",
    },
    {
      name: "favorite albums",
      url: "https://www.last.fm/tag/favorite+albums",
    },
    {
      name: "alternative metal",
      url: "https://www.last.fm/tag/alternative+metal",
    },
    {
      name: "tool",
      url: "https://www.last.fm/tag/tool",
    },
    {
      name: "rock",
      url: "https://www.last.fm/tag/rock",
    },
    {
      name: "Masterpiece",
      url: "https://www.last.fm/tag/Masterpiece",
    },
    {
      name: "alternative",
      url: "https://www.last.fm/tag/alternative",
    },
  ],
  id: 999,
};

const albumBuena = {
  spotifyId: "6DPdEaZ0KDBCCgXyy4q8bi",
  name: "Buena Vista Social Club",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b2732a896bf89ee1e87f1a774cb6",
    "https://i.scdn.co/image/ab67616d00001e022a896bf89ee1e87f1a774cb6",
    "https://i.scdn.co/image/ab67616d000048512a896bf89ee1e87f1a774cb6",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b2732a896bf89ee1e87f1a774cb6",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e022a896bf89ee1e87f1a774cb6",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d000048512a896bf89ee1e87f1a774cb6",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/6DPdEaZ0KDBCCgXyy4q8bi",
  spotifyReleaseDate: new Date("1997-06-22T22:00:00.000Z"),
  spotifyArtistsIds: ["11kBu957KTYoAltZHDm8gW"],
  spotifyPopularity: 62,
  spotifyGenres: [],
  spotifyUri: "spotify:album:6DPdEaZ0KDBCCgXyy4q8bi",
  albumTags: [],
  artists: [
    {
      name: "Buena Vista Social Club",
      spotifyId: "11kBu957KTYoAltZHDm8gW",
      spotifyUri: "spotify:artist:11kBu957KTYoAltZHDm8gW",
      spotifyUrl: "https://open.spotify.com/artist/11kBu957KTYoAltZHDm8gW",
      spotifyGenres: ["latin jazz", "musica tradicional cubana", "world"],
      spotifyPopularity: 61,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5ebe35db4d5803c5a4c77dd44db",
        "https://i.scdn.co/image/ab67616100005174e35db4d5803c5a4c77dd44db",
        "https://i.scdn.co/image/ab6761610000f178e35db4d5803c5a4c77dd44db",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebe35db4d5803c5a4c77dd44db",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174e35db4d5803c5a4c77dd44db",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178e35db4d5803c5a4c77dd44db",
          width: 160,
        },
      ],
      type: "artist",
      id: 1036,
    },
  ],
  lastfmTagsNames: [
    "latin",
    "cuban",
    "jazz",
    "buena vista social club",
    "cuba",
    "albums I own",
    "latin jazz",
    "world",
    "favorite albums",
    "1997",
    "90s",
    "son",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "latin",
      url: "https://www.last.fm/tag/latin",
    },
    {
      name: "cuban",
      url: "https://www.last.fm/tag/cuban",
    },
    {
      name: "jazz",
      url: "https://www.last.fm/tag/jazz",
    },
    {
      name: "buena vista social club",
      url: "https://www.last.fm/tag/buena+vista+social+club",
    },
    {
      name: "cuba",
      url: "https://www.last.fm/tag/cuba",
    },
    {
      name: "albums I own",
      url: "https://www.last.fm/tag/albums+I+own",
    },
    {
      name: "latin jazz",
      url: "https://www.last.fm/tag/latin+jazz",
    },
    {
      name: "world",
      url: "https://www.last.fm/tag/world",
    },
    {
      name: "favorite albums",
      url: "https://www.last.fm/tag/favorite+albums",
    },
    {
      name: "1997",
      url: "https://www.last.fm/tag/1997",
    },
    {
      name: "90s",
      url: "https://www.last.fm/tag/90s",
    },
    {
      name: "son",
      url: "https://www.last.fm/tag/son",
    },
  ],
  id: 1007,
};

const albumCure = {
  spotifyId: "6DZNOsLXIU2zOQfQDwDpIS",
  name: "Disintegration (Remastered)",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273858ed9e2832801189187391a",
    "https://i.scdn.co/image/ab67616d00001e02858ed9e2832801189187391a",
    "https://i.scdn.co/image/ab67616d00004851858ed9e2832801189187391a",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273858ed9e2832801189187391a",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02858ed9e2832801189187391a",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851858ed9e2832801189187391a",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/6DZNOsLXIU2zOQfQDwDpIS",
  spotifyReleaseDate: new Date("1989-05-01T22:00:00.000Z"),
  spotifyArtistsIds: ["7bu3H8JO7d0UbMoVzbo70s"],
  spotifyPopularity: 43,
  spotifyGenres: [],
  spotifyUri: "spotify:album:6DZNOsLXIU2zOQfQDwDpIS",
  albumTags: [],
  artists: [
    {
      name: "The Cure",
      spotifyId: "7bu3H8JO7d0UbMoVzbo70s",
      spotifyUri: "spotify:artist:7bu3H8JO7d0UbMoVzbo70s",
      spotifyUrl: "https://open.spotify.com/artist/7bu3H8JO7d0UbMoVzbo70s",
      spotifyGenres: ["new wave", "permanent wave", "rock", "uk post-punk"],
      spotifyPopularity: 72,
      spotifyImgs: [
        "https://i.scdn.co/image/7ca743e822b80133971ccf5c70fcbd77a4f4f508",
        "https://i.scdn.co/image/2cb2e14783685fd3d27006891aaaa35fc53cd82d",
        "https://i.scdn.co/image/9e1ed6613ac0ef103fbfca3c11ff35fec8d9c6b1",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/7ca743e822b80133971ccf5c70fcbd77a4f4f508",
          width: 640,
        },
        {
          height: 200,
          url: "https://i.scdn.co/image/2cb2e14783685fd3d27006891aaaa35fc53cd82d",
          width: 200,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/9e1ed6613ac0ef103fbfca3c11ff35fec8d9c6b1",
          width: 64,
        },
      ],
      type: "artist",
      id: 1196,
    },
  ],
  lastfmTagsNames: [
    "1989",
    "alternative",
    "post-punk",
    "rock",
    "80s",
    "alternative rock",
    "new wave",
    "Gothic",
    "Gothic Rock",
    "shit",
    "1980s",
    "1001 Albums You Must Hear Before You Die",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "1989",
      url: "https://www.last.fm/tag/1989",
    },
    {
      name: "alternative",
      url: "https://www.last.fm/tag/alternative",
    },
    {
      name: "post-punk",
      url: "https://www.last.fm/tag/post-punk",
    },
    {
      name: "rock",
      url: "https://www.last.fm/tag/rock",
    },
    {
      name: "80s",
      url: "https://www.last.fm/tag/80s",
    },
    {
      name: "alternative rock",
      url: "https://www.last.fm/tag/alternative+rock",
    },
    {
      name: "new wave",
      url: "https://www.last.fm/tag/new+wave",
    },
    {
      name: "Gothic",
      url: "https://www.last.fm/tag/Gothic",
    },
    {
      name: "Gothic Rock",
      url: "https://www.last.fm/tag/Gothic+Rock",
    },
    {
      name: "shit",
      url: "https://www.last.fm/tag/shit",
    },
    {
      name: "1980s",
      url: "https://www.last.fm/tag/1980s",
    },
    {
      name: "1001 Albums You Must Hear Before You Die",
      url: "https://www.last.fm/tag/1001+Albums+You+Must+Hear+Before+You+Die",
    },
  ],
  id: 1180,
};
const albumViolator = {
  spotifyId: "0Tg76MY2wNK4j37iCb6qyH",
  name: "Violator (Deluxe)",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273234bbbad4dce31cd2950af3e",
    "https://i.scdn.co/image/ab67616d00001e02234bbbad4dce31cd2950af3e",
    "https://i.scdn.co/image/ab67616d00004851234bbbad4dce31cd2950af3e",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273234bbbad4dce31cd2950af3e",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02234bbbad4dce31cd2950af3e",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851234bbbad4dce31cd2950af3e",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/0Tg76MY2wNK4j37iCb6qyH",
  spotifyReleaseDate: new Date("1990-03-18T23:00:00.000Z"),
  spotifyArtistsIds: ["762310PdDnwsDxAQxzQkfX"],
  spotifyPopularity: 57,
  spotifyGenres: [],
  spotifyUri: "spotify:album:0Tg76MY2wNK4j37iCb6qyH",
  albumTags: [],
  artists: [
    {
      name: "Depeche Mode",
      spotifyId: "762310PdDnwsDxAQxzQkfX",
      spotifyUri: "spotify:artist:762310PdDnwsDxAQxzQkfX",
      spotifyUrl: "https://open.spotify.com/artist/762310PdDnwsDxAQxzQkfX",
      spotifyGenres: [
        "dance rock",
        "new romantic",
        "new wave",
        "permanent wave",
        "synthpop",
      ],
      spotifyPopularity: 72,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb8ada6bad4c9b276b7fd24874",
        "https://i.scdn.co/image/ab676161000051748ada6bad4c9b276b7fd24874",
        "https://i.scdn.co/image/ab6761610000f1788ada6bad4c9b276b7fd24874",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb8ada6bad4c9b276b7fd24874",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051748ada6bad4c9b276b7fd24874",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1788ada6bad4c9b276b7fd24874",
          width: 160,
        },
      ],
      type: "artist",
      id: 947,
    },
  ],
  lastfmTagsNames: [
    "80s",
    "synth pop",
    "1990",
    "electronic",
    "new wave",
    "Gothic",
    "90s",
    "synthpop",
    "sensual",
    "sexual",
    "amor",
    "drogas",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "80s",
      url: "https://www.last.fm/tag/80s",
    },
    {
      name: "synth pop",
      url: "https://www.last.fm/tag/synth+pop",
    },
    {
      name: "1990",
      url: "https://www.last.fm/tag/1990",
    },
    {
      name: "electronic",
      url: "https://www.last.fm/tag/electronic",
    },
    {
      name: "new wave",
      url: "https://www.last.fm/tag/new+wave",
    },
    {
      name: "Gothic",
      url: "https://www.last.fm/tag/Gothic",
    },
    {
      name: "90s",
      url: "https://www.last.fm/tag/90s",
    },
    {
      name: "synthpop",
      url: "https://www.last.fm/tag/synthpop",
    },
    {
      name: "sensual",
      url: "https://www.last.fm/tag/sensual",
    },
    {
      name: "sexual",
      url: "https://www.last.fm/tag/sexual",
    },
    {
      name: "amor",
      url: "https://www.last.fm/tag/amor",
    },
    {
      name: "drogas",
      url: "https://www.last.fm/tag/drogas",
    },
  ],
  id: 1165,
};

const albumCourt = {
  spotifyId: "6tVg2Wl9hVKMpHYcAl2V2M",
  name: "In The Court Of The Crimson King (Expanded & Remastered Original Album Mix)",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b2730e36a62897cf3f5937bf9c16",
    "https://i.scdn.co/image/ab67616d00001e020e36a62897cf3f5937bf9c16",
    "https://i.scdn.co/image/ab67616d000048510e36a62897cf3f5937bf9c16",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b2730e36a62897cf3f5937bf9c16",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e020e36a62897cf3f5937bf9c16",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d000048510e36a62897cf3f5937bf9c16",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/6tVg2Wl9hVKMpHYcAl2V2M",
  spotifyReleaseDate: new Date("1969-10-09T23:00:00.000Z"),
  spotifyArtistsIds: ["7M1FPw29m5FbicYzS2xdpi"],
  spotifyPopularity: 50,
  spotifyGenres: [],
  spotifyUri: "spotify:album:6tVg2Wl9hVKMpHYcAl2V2M",
  albumTags: [],
  artists: [
    {
      name: "King Crimson",
      spotifyId: "7M1FPw29m5FbicYzS2xdpi",
      spotifyUri: "spotify:artist:7M1FPw29m5FbicYzS2xdpi",
      spotifyUrl: "https://open.spotify.com/artist/7M1FPw29m5FbicYzS2xdpi",
      spotifyGenres: [
        "album rock",
        "art rock",
        "classic rock",
        "instrumental rock",
        "jazz fusion",
        "jazz rock",
        "progressive rock",
        "psychedelic rock",
        "rock",
        "symphonic rock",
        "zolo",
      ],
      spotifyPopularity: 53,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb7c1c2fcf5a73dbfa60a40a18",
        "https://i.scdn.co/image/ab676161000051747c1c2fcf5a73dbfa60a40a18",
        "https://i.scdn.co/image/ab6761610000f1787c1c2fcf5a73dbfa60a40a18",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb7c1c2fcf5a73dbfa60a40a18",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051747c1c2fcf5a73dbfa60a40a18",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1787c1c2fcf5a73dbfa60a40a18",
          width: 160,
        },
      ],
      type: "artist",
      id: 941,
    },
  ],
  lastfmTagsNames: ["FUCKING AWESOME", "1969", "Listened to"],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HN",
    "HR",
    "HT",
    "HU",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "KE",
    "KG",
    "KI",
    "KM",
    "KN",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "FUCKING AWESOME",
      url: "https://www.last.fm/tag/FUCKING+AWESOME",
    },
    {
      name: "1969",
      url: "https://www.last.fm/tag/1969",
    },
    {
      name: "Listened to",
      url: "https://www.last.fm/tag/Listened+to",
    },
  ],
  id: 897,
};
const albumMad = {
  spotifyId: "19bQiwEKhXUBJWY6oV3KZk",
  name: "Madvillainy",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b27374dc897ea75402db37ef239a",
    "https://i.scdn.co/image/ab67616d00001e0274dc897ea75402db37ef239a",
    "https://i.scdn.co/image/ab67616d0000485174dc897ea75402db37ef239a",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b27374dc897ea75402db37ef239a",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e0274dc897ea75402db37ef239a",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d0000485174dc897ea75402db37ef239a",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/19bQiwEKhXUBJWY6oV3KZk",
  spotifyReleaseDate: new Date("2004-03-23T23:00:00.000Z"),
  spotifyArtistsIds: [
    "2aoFQUeHD1U7pL098lRsDU",
    "5LhTec3c7dcqBvpLRWbMcf",
    "2pAWfrd7WFF3XhVt9GooDL",
  ],
  spotifyPopularity: 65,
  spotifyGenres: [],
  spotifyUri: "spotify:album:19bQiwEKhXUBJWY6oV3KZk",
  albumTags: [],
  artists: [
    {
      name: "Madvillain",
      spotifyId: "2aoFQUeHD1U7pL098lRsDU",
      spotifyUri: "spotify:artist:2aoFQUeHD1U7pL098lRsDU",
      spotifyUrl: "https://open.spotify.com/artist/2aoFQUeHD1U7pL098lRsDU",
      spotifyGenres: [
        "abstract hip hop",
        "alternative hip hop",
        "hip hop",
        "psychedelic hip hop",
        "rap",
      ],
      spotifyPopularity: 62,
      spotifyImgs: [
        "https://i.scdn.co/image/bc99e9cb1976fcecb929d819b3dfc6f6fabca500",
        "https://i.scdn.co/image/9d7ed68679a970b86faaea230d16334baba5ed4b",
        "https://i.scdn.co/image/3c14d3a5bf0dbc50595b6d5001633aae9d9e2b5f",
        "https://i.scdn.co/image/ad65acde29d51f7f62a9307815d5b9029be3bb64",
      ],
      spotifyArtistImgs: [
        {
          height: 1000,
          url: "https://i.scdn.co/image/bc99e9cb1976fcecb929d819b3dfc6f6fabca500",
          width: 1000,
        },
        {
          height: 640,
          url: "https://i.scdn.co/image/9d7ed68679a970b86faaea230d16334baba5ed4b",
          width: 640,
        },
        {
          height: 200,
          url: "https://i.scdn.co/image/3c14d3a5bf0dbc50595b6d5001633aae9d9e2b5f",
          width: 200,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ad65acde29d51f7f62a9307815d5b9029be3bb64",
          width: 64,
        },
      ],
      type: "artist",
      id: 1148,
    },
    {
      name: "MF DOOM",
      spotifyId: "2pAWfrd7WFF3XhVt9GooDL",
      spotifyUri: "spotify:artist:2pAWfrd7WFF3XhVt9GooDL",
      spotifyUrl: "https://open.spotify.com/artist/2pAWfrd7WFF3XhVt9GooDL",
      spotifyGenres: [
        "alternative hip hop",
        "east coast hip hop",
        "hip hop",
        "rap",
      ],
      spotifyPopularity: 71,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eb1ca139a174e216880498dc16",
        "https://i.scdn.co/image/ab676161000051741ca139a174e216880498dc16",
        "https://i.scdn.co/image/ab6761610000f1781ca139a174e216880498dc16",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb1ca139a174e216880498dc16",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051741ca139a174e216880498dc16",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1781ca139a174e216880498dc16",
          width: 160,
        },
      ],
      type: "artist",
      id: 1150,
    },
    {
      name: "Madlib",
      spotifyId: "5LhTec3c7dcqBvpLRWbMcf",
      spotifyUri: "spotify:artist:5LhTec3c7dcqBvpLRWbMcf",
      spotifyUrl: "https://open.spotify.com/artist/5LhTec3c7dcqBvpLRWbMcf",
      spotifyGenres: [
        "abstract hip hop",
        "alternative hip hop",
        "hip hop",
        "psychedelic hip hop",
      ],
      spotifyPopularity: 66,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5ebdb860c843b90fdea28f670d6",
        "https://i.scdn.co/image/ab67616100005174db860c843b90fdea28f670d6",
        "https://i.scdn.co/image/ab6761610000f178db860c843b90fdea28f670d6",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebdb860c843b90fdea28f670d6",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174db860c843b90fdea28f670d6",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178db860c843b90fdea28f670d6",
          width: 160,
        },
      ],
      type: "artist",
      id: 1149,
    },
  ],
  lastfmTagsNames: [
    "Hip-Hop",
    "2004",
    "hip hop",
    "rap",
    "albums I own",
    "Stones throw",
    "abstract hip hop",
    "favourite albums",
    "jazz rap",
    "mf doom",
    "experimental hip hop",
    "underground hip-hop",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "Hip-Hop",
      url: "https://www.last.fm/tag/Hip-Hop",
    },
    {
      name: "2004",
      url: "https://www.last.fm/tag/2004",
    },
    {
      name: "hip hop",
      url: "https://www.last.fm/tag/hip+hop",
    },
    {
      name: "rap",
      url: "https://www.last.fm/tag/rap",
    },
    {
      name: "albums I own",
      url: "https://www.last.fm/tag/albums+I+own",
    },
    {
      name: "Stones throw",
      url: "https://www.last.fm/tag/Stones+throw",
    },
    {
      name: "abstract hip hop",
      url: "https://www.last.fm/tag/abstract+hip+hop",
    },
    {
      name: "favourite albums",
      url: "https://www.last.fm/tag/favourite+albums",
    },
    {
      name: "jazz rap",
      url: "https://www.last.fm/tag/jazz+rap",
    },
    {
      name: "mf doom",
      url: "https://www.last.fm/tag/mf+doom",
    },
    {
      name: "experimental hip hop",
      url: "https://www.last.fm/tag/experimental+hip+hop",
    },
    {
      name: "underground hip-hop",
      url: "https://www.last.fm/tag/underground+hip-hop",
    },
  ],
  id: 1121,
};
const albumApe = {
  spotifyId: "4YzYXXM2GSzsp0hsgVBBrU",
  name: "The Ape Of Naples",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273b9b111f3e3cd5ebbd1628d9f",
    "https://i.scdn.co/image/ab67616d00001e02b9b111f3e3cd5ebbd1628d9f",
    "https://i.scdn.co/image/ab67616d00004851b9b111f3e3cd5ebbd1628d9f",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273b9b111f3e3cd5ebbd1628d9f",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02b9b111f3e3cd5ebbd1628d9f",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851b9b111f3e3cd5ebbd1628d9f",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/4YzYXXM2GSzsp0hsgVBBrU",
  spotifyReleaseDate: new Date("2016-09-29T22:00:00.000Z"),
  spotifyArtistsIds: ["37KB5e6cGsN1AQAB9Omm1U"],
  spotifyPopularity: 29,
  spotifyGenres: [],
  spotifyUri: "spotify:album:4YzYXXM2GSzsp0hsgVBBrU",
  albumTags: [],
  artists: [
    {
      name: "Coil",
      spotifyId: "37KB5e6cGsN1AQAB9Omm1U",
      spotifyUri: "spotify:artist:37KB5e6cGsN1AQAB9Omm1U",
      spotifyUrl: "https://open.spotify.com/artist/37KB5e6cGsN1AQAB9Omm1U",
      spotifyGenres: [
        "british experimental",
        "british industrial",
        "dark jazz",
        "dub metal",
        "experimental",
        "experimental rock",
        "industrial",
        "new isolationism",
        "ritual ambient",
        "uk experimental electronic",
      ],
      spotifyPopularity: 33,
      spotifyImgs: [
        "https://i.scdn.co/image/8f10b786e295476593860cb018b112a8b9f264f1",
        "https://i.scdn.co/image/7aa4d01666902444c7733bf77024e38273f3aac7",
        "https://i.scdn.co/image/463df724958da98aeded23be0baec8f864b028d6",
      ],
      spotifyArtistImgs: [
        {
          height: 495,
          url: "https://i.scdn.co/image/8f10b786e295476593860cb018b112a8b9f264f1",
          width: 500,
        },
        {
          height: 198,
          url: "https://i.scdn.co/image/7aa4d01666902444c7733bf77024e38273f3aac7",
          width: 200,
        },
        {
          height: 63,
          url: "https://i.scdn.co/image/463df724958da98aeded23be0baec8f864b028d6",
          width: 64,
        },
      ],
      type: "artist",
      id: 1133,
    },
  ],
  lastfmTagsNames: [
    "experimental",
    "electronic",
    "ambient",
    "dark ambient",
    "2005",
    "industrial",
    "Avant-Garde",
    "clinically romantic",
    "Post-Industrial",
    "experimental industrial",
    "achingly intelligent",
    "ambient industrial",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "experimental",
      url: "https://www.last.fm/tag/experimental",
    },
    {
      name: "electronic",
      url: "https://www.last.fm/tag/electronic",
    },
    {
      name: "ambient",
      url: "https://www.last.fm/tag/ambient",
    },
    {
      name: "dark ambient",
      url: "https://www.last.fm/tag/dark+ambient",
    },
    {
      name: "2005",
      url: "https://www.last.fm/tag/2005",
    },
    {
      name: "industrial",
      url: "https://www.last.fm/tag/industrial",
    },
    {
      name: "Avant-Garde",
      url: "https://www.last.fm/tag/Avant-Garde",
    },
    {
      name: "clinically romantic",
      url: "https://www.last.fm/tag/clinically+romantic",
    },
    {
      name: "Post-Industrial",
      url: "https://www.last.fm/tag/Post-Industrial",
    },
    {
      name: "experimental industrial",
      url: "https://www.last.fm/tag/experimental+industrial",
    },
    {
      name: "achingly intelligent",
      url: "https://www.last.fm/tag/achingly+intelligent",
    },
    {
      name: "ambient industrial",
      url: "https://www.last.fm/tag/ambient+industrial",
    },
  ],
  id: 1106,
};
const albumMassive = {
  spotifyId: "49MNmJhZQewjt06rpwp6QR",
  name: "Mezzanine",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b2732fcb0a3c7a66e516b11cd26e",
    "https://i.scdn.co/image/ab67616d00001e022fcb0a3c7a66e516b11cd26e",
    "https://i.scdn.co/image/ab67616d000048512fcb0a3c7a66e516b11cd26e",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b2732fcb0a3c7a66e516b11cd26e",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e022fcb0a3c7a66e516b11cd26e",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d000048512fcb0a3c7a66e516b11cd26e",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/49MNmJhZQewjt06rpwp6QR",
  spotifyReleaseDate: new Date("1997-12-31T23:00:00.000Z"),
  spotifyArtistsIds: ["6FXMGgJwohJLUSr5nVlf9X"],
  spotifyPopularity: 58,
  spotifyGenres: [],
  spotifyUri: "spotify:album:49MNmJhZQewjt06rpwp6QR",
  albumTags: [],
  artists: [
    {
      name: "Massive Attack",
      spotifyId: "6FXMGgJwohJLUSr5nVlf9X",
      spotifyUri: "spotify:artist:6FXMGgJwohJLUSr5nVlf9X",
      spotifyUrl: "https://open.spotify.com/artist/6FXMGgJwohJLUSr5nVlf9X",
      spotifyGenres: ["big beat", "downtempo", "electronica", "trip hop"],
      spotifyPopularity: 61,
      spotifyImgs: [
        "https://i.scdn.co/image/c8bbeedb05f38ae5cb982a7daf4bf7129cca892c",
        "https://i.scdn.co/image/52c2a824e84f4e8adf0b12418f9f8306b4b5b77a",
        "https://i.scdn.co/image/0d6b7677f8291c5158bdace8a6e027880c527c2a",
        "https://i.scdn.co/image/c055290bb6e97a589d8ca659cd452a8e9831c2c4",
      ],
      spotifyArtistImgs: [
        {
          height: 1335,
          url: "https://i.scdn.co/image/c8bbeedb05f38ae5cb982a7daf4bf7129cca892c",
          width: 1000,
        },
        {
          height: 855,
          url: "https://i.scdn.co/image/52c2a824e84f4e8adf0b12418f9f8306b4b5b77a",
          width: 640,
        },
        {
          height: 267,
          url: "https://i.scdn.co/image/0d6b7677f8291c5158bdace8a6e027880c527c2a",
          width: 200,
        },
        {
          height: 85,
          url: "https://i.scdn.co/image/c055290bb6e97a589d8ca659cd452a8e9831c2c4",
          width: 64,
        },
      ],
      type: "artist",
      id: 930,
    },
  ],
  lastfmTagsNames: [
    "trip-hop",
    "electronic",
    "albums I own",
    "chillout",
    "electronica",
    "1998",
    "trip hop",
    "favorite albums",
    "downtempo",
    "favourite albums",
    "90s",
    "alternative",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "trip-hop",
      url: "https://www.last.fm/tag/trip-hop",
    },
    {
      name: "electronic",
      url: "https://www.last.fm/tag/electronic",
    },
    {
      name: "albums I own",
      url: "https://www.last.fm/tag/albums+I+own",
    },
    {
      name: "chillout",
      url: "https://www.last.fm/tag/chillout",
    },
    {
      name: "electronica",
      url: "https://www.last.fm/tag/electronica",
    },
    {
      name: "1998",
      url: "https://www.last.fm/tag/1998",
    },
    {
      name: "trip hop",
      url: "https://www.last.fm/tag/trip+hop",
    },
    {
      name: "favorite albums",
      url: "https://www.last.fm/tag/favorite+albums",
    },
    {
      name: "downtempo",
      url: "https://www.last.fm/tag/downtempo",
    },
    {
      name: "favourite albums",
      url: "https://www.last.fm/tag/favourite+albums",
    },
    {
      name: "90s",
      url: "https://www.last.fm/tag/90s",
    },
    {
      name: "alternative",
      url: "https://www.last.fm/tag/alternative",
    },
  ],
  id: 902,
};

const albumPleasures = {
  spotifyId: "5Dgqy4bBg09Rdw7CQM545s",
  name: "Unknown Pleasures",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b27327cc8b0ed297111f53009772",
    "https://i.scdn.co/image/ab67616d00001e0227cc8b0ed297111f53009772",
    "https://i.scdn.co/image/ab67616d0000485127cc8b0ed297111f53009772",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b27327cc8b0ed297111f53009772",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e0227cc8b0ed297111f53009772",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d0000485127cc8b0ed297111f53009772",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/5Dgqy4bBg09Rdw7CQM545s",
  spotifyReleaseDate: new Date("1979-06-14T22:00:00.000Z"),
  spotifyArtistsIds: ["432R46LaYsJZV2Gmc4jUV5"],
  spotifyPopularity: 43,
  spotifyGenres: [],
  spotifyUri: "spotify:album:5Dgqy4bBg09Rdw7CQM545s",
  albumTags: [],
  artists: [
    {
      name: "Joy Division",
      spotifyId: "432R46LaYsJZV2Gmc4jUV5",
      spotifyUri: "spotify:artist:432R46LaYsJZV2Gmc4jUV5",
      spotifyUrl: "https://open.spotify.com/artist/432R46LaYsJZV2Gmc4jUV5",
      spotifyGenres: [
        "alternative rock",
        "art rock",
        "madchester",
        "new wave",
        "post-punk",
        "rock",
        "uk post-punk",
      ],
      spotifyPopularity: 61,
      spotifyImgs: [
        "https://i.scdn.co/image/5eeddd733170399db794d2c430a8d2cde7ae1425",
        "https://i.scdn.co/image/d3c6bcb07a5ecddf86e791fa901bf3792fe6e6c7",
        "https://i.scdn.co/image/d384ebd3d3fda0ad219fed6b9014a59e65fbb385",
        "https://i.scdn.co/image/1b5195d5e9b5aac07fb0c801deb1926138222036",
      ],
      spotifyArtistImgs: [
        {
          height: 658,
          url: "https://i.scdn.co/image/5eeddd733170399db794d2c430a8d2cde7ae1425",
          width: 1000,
        },
        {
          height: 421,
          url: "https://i.scdn.co/image/d3c6bcb07a5ecddf86e791fa901bf3792fe6e6c7",
          width: 640,
        },
        {
          height: 132,
          url: "https://i.scdn.co/image/d384ebd3d3fda0ad219fed6b9014a59e65fbb385",
          width: 200,
        },
        {
          height: 42,
          url: "https://i.scdn.co/image/1b5195d5e9b5aac07fb0c801deb1926138222036",
          width: 64,
        },
      ],
      type: "artist",
      id: 942,
    },
  ],
  lastfmTagsNames: [
    "post-punk",
    "new wave",
    "albums I own",
    "1979",
    "favourite albums",
    "favorite albums",
    "70s",
    "alternative",
    "british",
    "rock",
    "Gothic Rock",
    "Gothic",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "post-punk",
      url: "https://www.last.fm/tag/post-punk",
    },
    {
      name: "new wave",
      url: "https://www.last.fm/tag/new+wave",
    },
    {
      name: "albums I own",
      url: "https://www.last.fm/tag/albums+I+own",
    },
    {
      name: "1979",
      url: "https://www.last.fm/tag/1979",
    },
    {
      name: "favourite albums",
      url: "https://www.last.fm/tag/favourite+albums",
    },
    {
      name: "favorite albums",
      url: "https://www.last.fm/tag/favorite+albums",
    },
    {
      name: "70s",
      url: "https://www.last.fm/tag/70s",
    },
    {
      name: "alternative",
      url: "https://www.last.fm/tag/alternative",
    },
    {
      name: "british",
      url: "https://www.last.fm/tag/british",
    },
    {
      name: "rock",
      url: "https://www.last.fm/tag/rock",
    },
    {
      name: "Gothic Rock",
      url: "https://www.last.fm/tag/Gothic+Rock",
    },
    {
      name: "Gothic",
      url: "https://www.last.fm/tag/Gothic",
    },
  ],
  id: 1073,
};

const albumRainbows = {
  spotifyId: "5vkqYmiPBYLaalcmjujWxK",
  name: "In Rainbows",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273de3c04b5fc750b68899b20a9",
    "https://i.scdn.co/image/ab67616d00001e02de3c04b5fc750b68899b20a9",
    "https://i.scdn.co/image/ab67616d00004851de3c04b5fc750b68899b20a9",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273de3c04b5fc750b68899b20a9",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02de3c04b5fc750b68899b20a9",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851de3c04b5fc750b68899b20a9",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/5vkqYmiPBYLaalcmjujWxK",
  spotifyReleaseDate: new Date("2007-12-27T23:00:00.000Z"),
  spotifyArtistsIds: ["4Z8W4fKeB5YxbusRsdQVPb"],
  spotifyPopularity: 65,
  spotifyGenres: [],
  spotifyUri: "spotify:album:5vkqYmiPBYLaalcmjujWxK",
  albumTags: [],
  artists: [
    {
      name: "Radiohead",
      spotifyId: "4Z8W4fKeB5YxbusRsdQVPb",
      spotifyUri: "spotify:artist:4Z8W4fKeB5YxbusRsdQVPb",
      spotifyUrl: "https://open.spotify.com/artist/4Z8W4fKeB5YxbusRsdQVPb",
      spotifyGenres: [
        "alternative rock",
        "art rock",
        "melancholia",
        "oxford indie",
        "permanent wave",
        "rock",
      ],
      spotifyPopularity: 77,
      spotifyImgs: [
        "https://i.scdn.co/image/ab6761610000e5eba03696716c9ee605006047fd",
        "https://i.scdn.co/image/ab67616100005174a03696716c9ee605006047fd",
        "https://i.scdn.co/image/ab6761610000f178a03696716c9ee605006047fd",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eba03696716c9ee605006047fd",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174a03696716c9ee605006047fd",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178a03696716c9ee605006047fd",
          width: 160,
        },
      ],
      type: "artist",
      id: 964,
    },
  ],
  lastfmTagsNames: [
    "albums I own",
    "alternative",
    "alternative rock",
    "2007",
    "best of 2007",
    "rock",
    "favorite albums",
    "indie",
    "favourite albums",
    "radiohead",
    "british",
    "00s",
  ],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [
    {
      name: "albums I own",
      url: "https://www.last.fm/tag/albums+I+own",
    },
    {
      name: "alternative",
      url: "https://www.last.fm/tag/alternative",
    },
    {
      name: "alternative rock",
      url: "https://www.last.fm/tag/alternative+rock",
    },
    {
      name: "2007",
      url: "https://www.last.fm/tag/2007",
    },
    {
      name: "best of 2007",
      url: "https://www.last.fm/tag/best+of+2007",
    },
    {
      name: "rock",
      url: "https://www.last.fm/tag/rock",
    },
    {
      name: "favorite albums",
      url: "https://www.last.fm/tag/favorite+albums",
    },
    {
      name: "indie",
      url: "https://www.last.fm/tag/indie",
    },
    {
      name: "favourite albums",
      url: "https://www.last.fm/tag/favourite+albums",
    },
    {
      name: "radiohead",
      url: "https://www.last.fm/tag/radiohead",
    },
    {
      name: "british",
      url: "https://www.last.fm/tag/british",
    },
    {
      name: "00s",
      url: "https://www.last.fm/tag/00s",
    },
  ],
  id: 1052,
};

const albumAnimals = {
  spotifyId: "21jUB9RqplD6OqtsTjKBnO",
  name: "Animals (2011 Remastered Version)",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b2731a0e01b6cd607bbc41c3ff4b",
    "https://i.scdn.co/image/ab67616d00001e021a0e01b6cd607bbc41c3ff4b",
    "https://i.scdn.co/image/ab67616d000048511a0e01b6cd607bbc41c3ff4b",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b2731a0e01b6cd607bbc41c3ff4b",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e021a0e01b6cd607bbc41c3ff4b",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d000048511a0e01b6cd607bbc41c3ff4b",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/21jUB9RqplD6OqtsTjKBnO",
  spotifyReleaseDate: new Date("1977-01-20T23:00:00.000Z"),
  spotifyArtistsIds: ["0k17h0D3J5VfsdmQ1iZtE9"],
  spotifyPopularity: 45,
  spotifyGenres: [],
  spotifyUri: "spotify:album:21jUB9RqplD6OqtsTjKBnO",
  albumTags: [],
  artists: [
    {
      name: "Pink Floyd",
      spotifyId: "0k17h0D3J5VfsdmQ1iZtE9",
      spotifyUri: "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9",
      spotifyUrl: "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9",
      spotifyGenres: [
        "album rock",
        "art rock",
        "classic rock",
        "progressive rock",
        "psychedelic rock",
        "rock",
        "symphonic rock",
      ],
      spotifyPopularity: 77,
      spotifyImgs: [
        "https://i.scdn.co/image/e69f71e2be4b67b82af90fb8e9d805715e0684fa",
        "https://i.scdn.co/image/d011c95081cd9a329e506abd7ded47535d524a07",
        "https://i.scdn.co/image/f0a39a8a196a87a7236bdcf8a8708f6d5d3547cc",
        "https://i.scdn.co/image/ec1fb7127168dbaa962404031409c5a293b95ec6",
      ],
      spotifyArtistImgs: [
        {
          height: 977,
          url: "https://i.scdn.co/image/e69f71e2be4b67b82af90fb8e9d805715e0684fa",
          width: 1000,
        },
        {
          height: 625,
          url: "https://i.scdn.co/image/d011c95081cd9a329e506abd7ded47535d524a07",
          width: 640,
        },
        {
          height: 195,
          url: "https://i.scdn.co/image/f0a39a8a196a87a7236bdcf8a8708f6d5d3547cc",
          width: 200,
        },
        {
          height: 63,
          url: "https://i.scdn.co/image/ec1fb7127168dbaa962404031409c5a293b95ec6",
          width: 64,
        },
      ],
      type: "artist",
      id: 1035,
    },
  ],
  lastfmTagsNames: ["art rock", "1977", "1970s", "mistagged", "album cover"],
  type: "album",
  markets: [
    "AD",
    "AL",
    "AM",
    "AT",
    "AZ",
    "BA",
    "BE",
    "BG",
    "BY",
    "CH",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DK",
    "DZ",
    "EE",
    "ES",
    "FI",
    "FR",
    "GB",
    "GE",
    "GR",
    "HR",
    "HU",
    "IE",
    "IS",
    "IT",
    "KG",
    "KZ",
    "LI",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MD",
    "ME",
    "MK",
    "MT",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "RS",
    "SE",
    "SI",
    "SK",
    "TJ",
    "TR",
    "UA",
    "UZ",
    "XK",
  ],
  lastfmTagsFull: [
    {
      name: "art rock",
      url: "https://www.last.fm/tag/art+rock",
    },
    {
      name: "1977",
      url: "https://www.last.fm/tag/1977",
    },
    {
      name: "1970s",
      url: "https://www.last.fm/tag/1970s",
    },
    {
      name: "mistagged",
      url: "https://www.last.fm/tag/mistagged",
    },
    {
      name: "album cover",
      url: "https://www.last.fm/tag/album+cover",
    },
  ],
  id: 1039,
};

const albumPatio = {
  spotifyId: "7oT1CbeyKlCJOsxmELnMMW",
  name: "El patio 40 Aniversario",
  spotifyCoverUrl: [
    "https://i.scdn.co/image/ab67616d0000b273a97a230cff27c947617b5a27",
    "https://i.scdn.co/image/ab67616d00001e02a97a230cff27c947617b5a27",
    "https://i.scdn.co/image/ab67616d00004851a97a230cff27c947617b5a27",
  ],
  spotifyCovers: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273a97a230cff27c947617b5a27",
      width: 640,
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02a97a230cff27c947617b5a27",
      width: 300,
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851a97a230cff27c947617b5a27",
      width: 64,
    },
  ],
  spotifyUrl: "https://open.spotify.com/album/7oT1CbeyKlCJOsxmELnMMW",
  spotifyReleaseDate: new Date("2015-04-27T22:00:00.000Z"),
  spotifyArtistsIds: ["5hlBb5u8K5D8yrL8jwZ7N9"],
  spotifyPopularity: 24,
  spotifyGenres: [],
  spotifyUri: "spotify:album:7oT1CbeyKlCJOsxmELnMMW",
  albumTags: [],
  artists: [
    {
      name: "Triana",
      spotifyId: "5hlBb5u8K5D8yrL8jwZ7N9",
      spotifyUri: "spotify:artist:5hlBb5u8K5D8yrL8jwZ7N9",
      spotifyUrl: "https://open.spotify.com/artist/5hlBb5u8K5D8yrL8jwZ7N9",
      spotifyGenres: [
        "cantautor",
        "rock andaluz",
        "rumba",
        "spanish new wave",
        "spanish prog",
      ],
      spotifyPopularity: 43,
      spotifyImgs: [
        "https://i.scdn.co/image/ab67616d0000b27339ef8bae7a9d8c89f12c7126",
        "https://i.scdn.co/image/ab67616d00001e0239ef8bae7a9d8c89f12c7126",
        "https://i.scdn.co/image/ab67616d0000485139ef8bae7a9d8c89f12c7126",
      ],
      spotifyArtistImgs: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b27339ef8bae7a9d8c89f12c7126",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e0239ef8bae7a9d8c89f12c7126",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d0000485139ef8bae7a9d8c89f12c7126",
          width: 64,
        },
      ],
      type: "artist",
      id: 1051,
    },
  ],
  lastfmTagsNames: [],
  type: "album",
  markets: [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CD",
    "CG",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PY",
    "QA",
    "RO",
    "RS",
    "RW",
    "SA",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TJ",
    "TL",
    "TN",
    "TR",
    "TT",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "UY",
    "UZ",
    "VC",
    "VE",
    "VN",
    "XK",
    "ZA",
    "ZM",
    "ZW",
  ],
  lastfmTagsFull: [],
  id: 1024,
};
const albums: Album[] = [
  albumMantle,
  albumDynamo,
  albumGlow,
  albumBad,
  albumLateralus,
  albumBuena,
  albumPatio,
  albumAnimals,
  albumApe,
  albumPleasures,
  albumMassive,
  albumRainbows,
  albumMad,
  albumCourt,
  albumCure,
  albumViolator,
];

export default shuffle(albums);
