name: Cypress End2End Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Test
    env:
      NEXT_PUBLIC_SPOTIFY_ID: ${{secrets.NEXT_PUBLIC_SPOTIFY_ID}}
      SPOTIFY_SECRET: ${{secrets.SPOTIFY_SECRET}}
      NEXT_PUBLIC_LAST_KEY: ${{secrets.NEXT_PUBLIC_LAST_KEY}}
      TEST_SPOTIFY_REFRESH: ${{secrets.TEST_SPOTIFY_REFRESH}}
      TEST_SPOTIFY_REFRESH_E2E: ${{secrets.TEST_SPOTIFY_REFRESH}}
      TEST_BASE_URL: "https://dev.spotmyfm.jorgeruizdev.com/"
    defaults:
      run:
        working-directory: ./NextJS
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./NextJS
          build: npm run build
          start: npm start
